using Microsoft.CodeAnalysis;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Dahomey.Cbor.Generator
{
    /// <summary>
    /// Renders an RFC 8610 CDDL schema for a context, as a second emit target over the same
    /// <see cref="TypeModel"/> list the registration emitter consumes.
    /// </summary>
    /// <remarks>
    /// This is a separate walk by necessity: <see cref="Emitter"/> registers one converter per type
    /// keyed on <c>typeof(T)</c> and resolves members through <c>DelegateMemberMapping</c> at run time,
    /// so there is no per-member emit site a schema could hang off.
    /// </remarks>
    internal static class CddlEmitter
    {
        public static string EmitSchema(
            IReadOnlyList<TypeModel> ordered,
            IReadOnlyList<ITypeSymbol> roots,
            GenerationOptions options,
            SourceProductionContext spc)
        {
            StringBuilder builder = new StringBuilder();

            builder.Append("; Generated by Dahomey.Cbor. Do not edit.\n");
            builder.Append("; Describes what the serializer WRITES: exact and closed.\n");
            builder.Append("; Member types follow their nullable annotations. A member declared non-nullable but left\n");
            builder.Append("; null at run time is written as F6 and will NOT validate against this schema.\n");
            builder.Append("; Assumes the discriminator key is \"_t\"; a custom discriminator convention is\n");
            builder.Append("; registered at run time and is not visible to the generator.\n");
            builder.Append("\n");

            Dictionary<string, TypeModel> byKey = new Dictionary<string, TypeModel>();

            foreach (TypeModel model in ordered)
            {
                byKey[model.Symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)] = model;
            }

            IReadOnlyDictionary<string, string> ruleNames = CddlNames.BuildRuleNames(ordered);

            foreach (TypeModel model in InEmissionOrder(ordered, roots))
            {
                if (model.Kind != TypeKind.Object)
                {
                    continue;
                }

                EmitObjectRule(builder, model, byKey, ruleNames, options, spc);
            }

            return builder.ToString();
        }

        /// <summary>
        /// Declared roots first, in the order written, then everything else in dependency order. The
        /// schema is a reviewable artifact, so a reordering diff is noise that hides real changes.
        /// </summary>
        private static IEnumerable<TypeModel> InEmissionOrder(
            IReadOnlyList<TypeModel> ordered, IReadOnlyList<ITypeSymbol> roots)
        {
            HashSet<string> emitted = new HashSet<string>();

            foreach (ITypeSymbol root in roots)
            {
                string key = root.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

                foreach (TypeModel model in ordered)
                {
                    if (model.Symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) == key
                        && emitted.Add(key))
                    {
                        yield return model;
                    }
                }
            }

            foreach (TypeModel model in ordered)
            {
                if (emitted.Add(model.Symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)))
                {
                    yield return model;
                }
            }
        }

        private static void EmitObjectRule(
            StringBuilder builder,
            TypeModel model,
            IReadOnlyDictionary<string, TypeModel> byKey,
            IReadOnlyDictionary<string, string> ruleNames,
            GenerationOptions options,
            SourceProductionContext spc)
        {
            string key = model.Symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            builder.Append(ruleNames[key]);
            builder.Append(" = {\n");

            foreach (MemberModel member in model.Members)
            {
                string? reference = CddlTypeReference.Render(member.Type, byKey, ruleNames, options);

                if (reference is null)
                {
                    spc.ReportDiagnostic(Diagnostic.Create(
                        Diagnostics.NoCddlRepresentation,
                        model.Symbol.Locations.FirstOrDefault(),
                        member.Type.ToDisplayString(),
                        model.Symbol.Name,
                        member.Name));
                    continue;
                }

                // Always quoted: a bareword member key is only legal CDDL when it matches RFC 8610's
                // `id` production, and this library's naming conventions and [CborProperty("...")]
                // both admit arbitrary strings (a leading digit, a space, ...) that `id` rejects. A
                // quoted `tstr` key is unconditionally valid, so quoting removes the failure mode
                // rather than trading it for a rarer one. This only covers text keys -- CborName is
                // always a string; an eventual IntKeyMap/Array emit path would key by CborIndex
                // instead, and integer keys are never quoted.
                builder.Append("  \"");
                builder.Append(member.CborName);
                builder.Append("\": ");
                builder.Append(reference);
                builder.Append(",\n");
            }

            builder.Append("}\n\n");
        }

        /// <summary>
        /// Wraps the schema in the partial class that exposes it. A verbatim string rather than a raw
        /// string literal, because generated code compiles under the consuming project's LangVersion
        /// and raw strings require C# 11.
        /// </summary>
        public static string EmitSource(INamedTypeSymbol contextSymbol, string schema)
        {
            StringBuilder builder = new StringBuilder();

            builder.AppendLine("// <auto-generated/>");
            builder.AppendLine("#nullable enable");
            builder.AppendLine();

            bool hasNamespace = !contextSymbol.ContainingNamespace.IsGlobalNamespace;
            string indent = hasNamespace ? "    " : string.Empty;

            if (hasNamespace)
            {
                builder.AppendLine($"namespace {contextSymbol.ContainingNamespace.ToDisplayString()}");
                builder.AppendLine("{");
            }

            builder.AppendLine($"{indent}public partial class {contextSymbol.Name}");
            builder.AppendLine($"{indent}{{");
            builder.AppendLine($"{indent}    /// <summary>RFC 8610 CDDL schema for the types declared on this context.</summary>");
            builder.AppendLine($"{indent}    public const string CddlSchema =");
            builder.AppendLine($"{indent}        @\"{schema.Replace("\"", "\"\"")}\";");
            builder.AppendLine($"{indent}}}");

            if (hasNamespace)
            {
                builder.AppendLine("}");
            }

            return builder.ToString();
        }
    }
}
