using Microsoft.CodeAnalysis;
using System.Collections.Generic;
using System.Text;

namespace Dahomey.Cbor.Generator
{
    /// <summary>
    /// Renders an RFC 8610 CDDL schema for a context, as a second emit target over the same
    /// <see cref="TypeModel"/> list the registration emitter consumes.
    /// </summary>
    /// <remarks>
    /// This is a separate walk by necessity: <see cref="Emitter"/> registers one converter per type
    /// keyed on <c>typeof(T)</c> and resolves members through <c>DelegateMemberMapping</c> at run time,
    /// so there is no per-member emit site a schema could hang off.
    /// </remarks>
    internal static class CddlEmitter
    {
        public static string EmitSchema(
            IReadOnlyList<TypeModel> ordered,
            IReadOnlyList<ITypeSymbol> roots,
            GenerationOptions options,
            SourceProductionContext spc)
        {
            StringBuilder builder = new StringBuilder();

            builder.AppendLine("; Generated by Dahomey.Cbor. Do not edit.");
            builder.AppendLine("; Describes what the serializer WRITES: exact and closed.");
            builder.AppendLine("; Assumes the discriminator key is \"_t\"; a custom discriminator convention is");
            builder.AppendLine("; registered at run time and is not visible to the generator.");

            return builder.ToString();
        }

        /// <summary>
        /// Wraps the schema in the partial class that exposes it. A verbatim string rather than a raw
        /// string literal, because generated code compiles under the consuming project's LangVersion
        /// and raw strings require C# 11.
        /// </summary>
        public static string EmitSource(INamedTypeSymbol contextSymbol, string schema)
        {
            StringBuilder builder = new StringBuilder();

            builder.AppendLine("// <auto-generated/>");
            builder.AppendLine("#nullable enable");
            builder.AppendLine();

            bool hasNamespace = !contextSymbol.ContainingNamespace.IsGlobalNamespace;
            string indent = hasNamespace ? "    " : string.Empty;

            if (hasNamespace)
            {
                builder.AppendLine($"namespace {contextSymbol.ContainingNamespace.ToDisplayString()}");
                builder.AppendLine("{");
            }

            builder.AppendLine($"{indent}public partial class {contextSymbol.Name}");
            builder.AppendLine($"{indent}{{");
            builder.AppendLine($"{indent}    /// <summary>RFC 8610 CDDL schema for the types declared on this context.</summary>");
            builder.AppendLine($"{indent}    public const string CddlSchema =");
            builder.AppendLine($"{indent}        @\"{schema.Replace("\"", "\"\"")}\";");
            builder.AppendLine($"{indent}}}");

            if (hasNamespace)
            {
                builder.AppendLine("}");
            }

            return builder.ToString();
        }
    }
}
