using Microsoft.CodeAnalysis;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Dahomey.Cbor.Generator
{
    /// <summary>
    /// Renders the generated half of a context: the <c>Configure</c> override plus a strongly-typed
    /// converter accessor per declared root type.
    /// </summary>
    internal static class Emitter
    {
        public static string Emit(
            INamedTypeSymbol contextSymbol,
            GenerationOptions options,
            IReadOnlyList<TypeModel> ordered,
            IReadOnlyList<ITypeSymbol> roots)
        {
            StringBuilder builder = new StringBuilder();

            builder.AppendLine("// <auto-generated/>");
            builder.AppendLine("#nullable enable");
            builder.AppendLine();
            builder.AppendLine("using Dahomey.Cbor;");
            builder.AppendLine("using Dahomey.Cbor.Attributes;");
            builder.AppendLine("using Dahomey.Cbor.Serialization;");
            builder.AppendLine("using Dahomey.Cbor.Serialization.Converters;");
            builder.AppendLine("using Dahomey.Cbor.Serialization.Converters.Mappings;");
            builder.AppendLine();

            bool hasNamespace = !contextSymbol.ContainingNamespace.IsGlobalNamespace;
            string indent = hasNamespace ? "    " : string.Empty;

            if (hasNamespace)
            {
                builder.AppendLine($"namespace {contextSymbol.ContainingNamespace.ToDisplayString()}");
                builder.AppendLine("{");
            }

            // A nested context needs every containing type reopened as a partial, or the generated
            // half lands as a top-level type and Configure is never implemented -- which surfaces as
            // CS0534 on the user's own class, naming nothing to do with generators.
            List<INamedTypeSymbol> containers = new List<INamedTypeSymbol>();

            for (INamedTypeSymbol? container = contextSymbol.ContainingType;
                 container is not null;
                 container = container.ContainingType)
            {
                containers.Insert(0, container);
            }

            foreach (INamedTypeSymbol container in containers)
            {
                builder.AppendLine($"{indent}{Accessibility(container)} partial {Keyword(container)} {NameWithTypeParameters(container)}");
                builder.AppendLine($"{indent}{{");
                indent += "    ";
            }

            // The declared accessibility, not a hardcoded `public`: a partial declaration whose parts
            // disagree is CS0262.
            builder.AppendLine($"{indent}{Accessibility(contextSymbol)} partial class {NameWithTypeParameters(contextSymbol)}");
            builder.AppendLine($"{indent}{{");

            EmitTypedAccessors(builder, indent, ordered, roots);
            EmitConfigure(builder, indent, options, ordered);
            EmitRegisterHelper(builder, indent);

            builder.AppendLine($"{indent}}}");

            for (int i = containers.Count - 1; i >= 0; i--)
            {
                indent = indent.Substring(4);
                builder.AppendLine($"{indent}}}");
            }

            if (hasNamespace)
            {
                builder.AppendLine("}");
            }

            return builder.ToString();
        }

        /// <summary>
        /// Hint name unique across the compilation. Keying on the simple name alone makes two
        /// same-named contexts in different namespaces collide, and the generator throws.
        /// </summary>
        public static string HintName(INamedTypeSymbol contextSymbol)
        {
            StringBuilder builder = new StringBuilder();

            foreach (char character in contextSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
            {
                builder.Append(char.IsLetterOrDigit(character) || character == '_' ? character : '.');
            }

            return builder.ToString().Trim('.') + ".CborContext.g.cs";
        }

        private static string Accessibility(INamedTypeSymbol symbol)
        {
            return symbol.DeclaredAccessibility switch
            {
                Microsoft.CodeAnalysis.Accessibility.Public => "public",
                Microsoft.CodeAnalysis.Accessibility.Internal => "internal",
                Microsoft.CodeAnalysis.Accessibility.Protected => "protected",
                Microsoft.CodeAnalysis.Accessibility.ProtectedOrInternal => "protected internal",
                Microsoft.CodeAnalysis.Accessibility.ProtectedAndInternal => "private protected",
                Microsoft.CodeAnalysis.Accessibility.Private => "private",
                _ => "internal",
            };
        }

        private static string Keyword(INamedTypeSymbol symbol)
        {
            return symbol.TypeKind switch
            {
                Microsoft.CodeAnalysis.TypeKind.Struct => symbol.IsRecord ? "record struct" : "struct",
                Microsoft.CodeAnalysis.TypeKind.Interface => "interface",
                _ => symbol.IsRecord ? "record" : "class",
            };
        }

        /// <summary>
        /// A generic container has to be reopened with its type parameters, or the partial does not
        /// match the user's declaration.
        /// </summary>
        private static string NameWithTypeParameters(INamedTypeSymbol symbol)
        {
            return symbol.TypeParameters.Length == 0
                ? symbol.Name
                : $"{symbol.Name}<{string.Join(", ", symbol.TypeParameters.Select(parameter => parameter.Name))}>";
        }

        /// <summary>
        /// One cached accessor per declared root, so callers reach a converter without a dictionary
        /// lookup on the hot path.
        /// </summary>
        private static void EmitTypedAccessors(
            StringBuilder builder,
            string indent,
            IReadOnlyList<TypeModel> ordered,
            IReadOnlyList<ITypeSymbol> roots)
        {
            HashSet<string> rootKeys = new HashSet<string>(
                roots.Select(r => r.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)));

            // Two roots with the same simple name in different namespaces would otherwise emit two
            // members with the same identifier, which is CS0102 on the user's own context.
            HashSet<string> usedAccessorNames = new HashSet<string>(StringComparer.Ordinal);

            foreach (TypeModel model in ordered)
            {
                string key = model.Symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

                if (!rootKeys.Contains(key) || model.Kind == TypeKind.Unsupported)
                {
                    continue;
                }

                string fullName = FullName(model.Symbol);
                string accessorName = UniqueAccessorName(model.Symbol, usedAccessorNames);
                string fieldName = "_" + char.ToLowerInvariant(accessorName[0]) + accessorName.Substring(1);

                builder.AppendLine($"{indent}    private ICborConverter<{fullName}>? {fieldName};");
                builder.AppendLine();
                builder.AppendLine($"{indent}    /// <summary>Converter for <see cref=\"{XmlName(fullName)}\"/>.</summary>");
                builder.AppendLine($"{indent}    public ICborConverter<{fullName}> {accessorName}");
                builder.AppendLine($"{indent}        => {fieldName} ??= GetConverter<{fullName}>();");
                builder.AppendLine();
            }
        }

        private static void EmitConfigure(
            StringBuilder builder,
            string indent,
            GenerationOptions options,
            IReadOnlyList<TypeModel> ordered)
        {
            builder.AppendLine($"{indent}    /// <summary>");
            builder.AppendLine($"{indent}    /// Registers every reachable type. Emitted in dependency order: converters resolve their");
            builder.AppendLine($"{indent}    /// member and element converters as they are constructed, so a dependency must already be");
            builder.AppendLine($"{indent}    /// registered by the time its dependent is built.");
            builder.AppendLine($"{indent}    /// </summary>");
            builder.AppendLine($"{indent}    protected override void Configure(CborOptions options)");
            builder.AppendLine($"{indent}    {{");
            builder.AppendLine($"{indent}        CborConverterRegistry converters = options.Registry.ConverterRegistry;");
            builder.AppendLine();

            EmitOptionAssignments(builder, indent, options);

            foreach (TypeModel model in ordered)
            {
                switch (model.Kind)
                {
                    case TypeKind.Primitive:
                    case TypeKind.Unsupported:
                        // Primitives resolve to concrete converters with no generic instantiation, so
                        // they need no registration. Unsupported types already produced a diagnostic.
                        continue;

                    case TypeKind.Enum:
                        EmitSimpleRegistration(builder, indent, model.Symbol,
                            $"new EnumConverter<{FullName(model.Symbol)}>(options)");
                        break;

                    case TypeKind.Nullable:
                        EmitSimpleRegistration(builder, indent, model.Symbol,
                            $"new NullableConverter<{FullName(model.UnderlyingType!)}>(options)");
                        break;

                    case TypeKind.ByteArray:
                        EmitSimpleRegistration(builder, indent, model.Symbol, "new ByteArrayConverter()");
                        break;

                    case TypeKind.Array:
                        EmitSimpleRegistration(builder, indent, model.Symbol,
                            $"new ArrayConverter<{FullName(model.ElementType!)}>(options)");
                        break;

                    case TypeKind.Collection:
                        EmitSimpleRegistration(builder, indent, model.Symbol,
                            $"new CollectionConverter<{FullName(model.Symbol)}, {FullName(model.ElementType!)}>(options)");
                        break;

                    case TypeKind.Dictionary:
                        EmitSimpleRegistration(builder, indent, model.Symbol,
                            $"new DictionaryConverter<{FullName(model.Symbol)}, {FullName(model.ElementType!)}, {FullName(model.ValueType!)}>(options)");
                        break;

                    case TypeKind.Object:
                        EmitObjectRegistration(builder, indent, model);
                        break;
                }
            }

            builder.AppendLine($"{indent}    }}");
        }

        private static void EmitOptionAssignments(StringBuilder builder, string indent, GenerationOptions options)
        {
            bool wrote = false;

            // A context does not disable the reflection fallback, so a type it does not declare is
            // still mapped by DefaultObjectMappingConvention -- which reads this. Leaving it unset
            // gave one document two naming conventions: declared types converted, fallback types
            // under their declared member names.
            if (options.NamingConvention is not null)
            {
                builder.AppendLine(
                    $"{indent}        options.DefaultNamingConvention = "
                    + $"new global::Dahomey.Cbor.Serialization.Conventions.{options.NamingConvention}();");
                wrote = true;
            }

            if (options.ObjectFormat != "StringKeyMap")
            {
                builder.AppendLine($"{indent}        options.ObjectFormat = CborObjectFormat.{options.ObjectFormat};");
                wrote = true;
            }

            if (options.DiscriminatorPolicy is not null)
            {
                builder.AppendLine($"{indent}        options.DiscriminatorPolicy = CborDiscriminatorPolicy.{options.DiscriminatorPolicy};");
                wrote = true;
            }

            if (options.DiscriminatorSemanticTag is not null)
            {
                builder.AppendLine($"{indent}        options.DiscriminatorSemanticTag = {options.DiscriminatorSemanticTag}UL;");
                wrote = true;
            }

            if (options.MaxDepth is not null)
            {
                builder.AppendLine($"{indent}        options.MaxDepth = {options.MaxDepth};");
                wrote = true;
            }

            if (wrote)
            {
                builder.AppendLine();
            }
        }

        /// <summary>
        /// The registration helper every emitted registration goes through, so that a refused
        /// registration is an exception rather than nothing at all.
        /// </summary>
        private static void EmitRegisterHelper(StringBuilder builder, string indent)
        {
            builder.AppendLine();
            builder.AppendLine($"{indent}    /// <summary>");
            builder.AppendLine($"{indent}    /// Registers one generated converter, refusing to continue if the registry already had a");
            builder.AppendLine($"{indent}    /// converter for that type.");
            builder.AppendLine($"{indent}    /// </summary>");
            builder.AppendLine($"{indent}    /// <remarks>");
            builder.AppendLine($"{indent}    /// RegisterConverter is TryAdd: an existing entry wins and the argument is dropped. Options");
            builder.AppendLine($"{indent}    /// that have already serialized something carry a converter for every type they touched, so a");
            builder.AppendLine($"{indent}    /// context constructed over them would register nothing, report nothing, and still look");
            builder.AppendLine($"{indent}    /// configured -- with every declared type served by the reflection path this context exists to");
            builder.AppendLine($"{indent}    /// replace, which is the path that fails under Native AOT.");
            builder.AppendLine($"{indent}    /// </remarks>");
            builder.AppendLine($"{indent}    private static void RegisterGeneratedConverter(");
            builder.AppendLine($"{indent}        CborConverterRegistry converters, global::System.Type type, ICborConverter converter)");
            builder.AppendLine($"{indent}    {{");
            builder.AppendLine($"{indent}        if (!converters.RegisterConverter(type, converter))");
            builder.AppendLine($"{indent}        {{");
            builder.AppendLine($"{indent}            throw new CborException(");
            builder.AppendLine($"{indent}                $\"These CborOptions already have a converter for {{type}}, so the generated one was \"");
            builder.AppendLine($"{indent}                + \"refused and the reflection path would be used instead. Construct the context before \"");
            builder.AppendLine($"{indent}                + \"the options are used to read or write, or give it its own CborOptions.\");");
            builder.AppendLine($"{indent}        }}");
            builder.AppendLine($"{indent}    }}");
        }

        private static void EmitSimpleRegistration(
            StringBuilder builder, string indent, ITypeSymbol type, string converterExpression)
        {
            builder.AppendLine($"{indent}        RegisterGeneratedConverter(converters, typeof({FullName(type)}), {converterExpression});");
            builder.AppendLine();
        }

        private static void EmitObjectRegistration(StringBuilder builder, string indent, TypeModel model)
        {
            string fullName = FullName(model.Symbol);

            builder.AppendLine($"{indent}        options.Registry.ObjectMappingRegistry.Register<{fullName}>(objectMapping =>");
            builder.AppendLine($"{indent}        {{");

            if (model.ObjectFormat != "StringKeyMap")
            {
                builder.AppendLine($"{indent}            objectMapping.SetObjectFormat(CborObjectFormat.{model.ObjectFormat});");
            }

            if (model.Members.Count == 0)
            {
                builder.AppendLine($"{indent}            objectMapping.SetMemberMappings(System.Array.Empty<IMemberMapping>());");
            }
            else
            {
                builder.AppendLine($"{indent}            objectMapping.SetMemberMappings(new IMemberMapping[]");
                builder.AppendLine($"{indent}            {{");

                foreach (MemberModel member in model.Members)
                {
                    EmitMemberMapping(builder, indent, model, member);
                }

                builder.AppendLine($"{indent}            }});");
            }

            // SetDiscriminator inserts the discriminator entry at index 0 of the member list, so it
            // must run after SetMemberMappings, which replaces that list wholesale.
            if (model.Discriminator is not null)
            {
                builder.AppendLine($"{indent}            objectMapping.SetDiscriminator({model.Discriminator});");
            }

            if (model.DiscriminatorPolicy is not null)
            {
                builder.AppendLine($"{indent}            objectMapping.SetDiscriminatorPolicy(CborDiscriminatorPolicy.{model.DiscriminatorPolicy});");
            }

            builder.AppendLine($"{indent}        }});");
            builder.AppendLine();

            string factory = model.CanInstantiate ? $", () => new {fullName}()" : string.Empty;
            builder.AppendLine($"{indent}        RegisterGeneratedConverter(");
            builder.AppendLine($"{indent}            converters, typeof({fullName}), new ObjectConverter<{fullName}>(options{factory}));");
            builder.AppendLine();
        }

        private static void EmitMemberMapping(
            StringBuilder builder, string indent, TypeModel model, MemberModel member)
        {
            string ownerName = FullName(model.Symbol);
            string memberTypeName = FullName(member.Type);

            bool isStruct = model.Symbol.TypeKind == Microsoft.CodeAnalysis.TypeKind.Struct;
            string mappingType = isStruct
                ? $"DelegateStructMemberMapping<{ownerName}, {memberTypeName}>"
                : $"DelegateMemberMapping<{ownerName}, {memberTypeName}>";

            // Structs need ref-taking accessors so mutations are not lost on a copy.
            string getter = isStruct
                ? $"(ref {ownerName} o) => o.{member.Name}"
                : $"o => o.{member.Name}";

            string setter = member.CanWrite
                ? isStruct
                    ? $"(ref {ownerName} o, {memberTypeName} v) => o.{member.Name} = v"
                    : $"(o, v) => o.{member.Name} = v"
                : "null";

            string key = member.CborIndex is not null
                ? $".SetMemberIndex({member.CborIndex})"
                : $".SetMemberName({Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(member.CborName, quote: true)})";

            builder.AppendLine($"{indent}                new {mappingType}(");
            builder.AppendLine($"{indent}                    converters,");
            builder.AppendLine($"{indent}                    {getter},");
            builder.AppendLine($"{indent}                    {setter}){key},");
        }

        private static string FullName(ITypeSymbol type)
        {
            return type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        }

        private static string XmlName(string fullName)
        {
            return fullName.Replace("global::", string.Empty).Replace('<', '{').Replace('>', '}');
        }

        /// <summary>
        /// Property name for a type's accessor: <c>Person</c>, and <c>ListOfPerson</c> for
        /// <c>List&lt;Person&gt;</c>, so closed generics get a legal, predictable identifier.
        /// </summary>
        /// <summary>
        /// Qualifies with the containing namespace only when the simple name is already taken, so the
        /// common case keeps the short, predictable identifier.
        /// </summary>
        private static string UniqueAccessorName(ITypeSymbol type, HashSet<string> used)
        {
            string name = AccessorName(type);

            if (used.Add(name))
            {
                return name;
            }

            string qualified = string.Concat(
                type.ContainingNamespace.ToDisplayString().Split('.').Where(part => part.Length > 0)) + name;

            if (used.Add(qualified))
            {
                return qualified;
            }

            for (int suffix = 2; ; suffix++)
            {
                string candidate = qualified + suffix;

                if (used.Add(candidate))
                {
                    return candidate;
                }
            }
        }

        private static string AccessorName(ITypeSymbol type)
        {
            if (type is IArrayTypeSymbol array)
            {
                return "ArrayOf" + AccessorName(array.ElementType);
            }

            if (type is INamedTypeSymbol { IsGenericType: true } named)
            {
                string baseName = named.Name;
                string arguments = string.Concat(named.TypeArguments.Select(AccessorName));
                return $"{baseName}Of{arguments}";
            }

            return type.Name;
        }
    }
}
