using Microsoft.CodeAnalysis;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Dahomey.Cbor.Generator
{
    /// <summary>
    /// Renders the generated half of a context: the <c>Configure</c> override plus a strongly-typed
    /// converter accessor per declared root type.
    /// </summary>
    internal static class Emitter
    {
        public static string Emit(
            INamedTypeSymbol contextSymbol,
            GenerationOptions options,
            IReadOnlyList<TypeModel> ordered,
            IReadOnlyList<ITypeSymbol> roots)
        {
            StringBuilder builder = new StringBuilder();

            builder.AppendLine("// <auto-generated/>");
            builder.AppendLine("#nullable enable");
            builder.AppendLine();
            builder.AppendLine("using Dahomey.Cbor;");
            builder.AppendLine("using Dahomey.Cbor.Attributes;");
            builder.AppendLine("using Dahomey.Cbor.Serialization;");
            builder.AppendLine("using Dahomey.Cbor.Serialization.Converters;");
            builder.AppendLine("using Dahomey.Cbor.Serialization.Converters.Mappings;");
            builder.AppendLine();

            string indent = OpenContextDeclaration(builder, contextSymbol);

            EmitTypedAccessors(builder, indent, ordered, roots);
            EmitConfigure(builder, indent, options, ordered);
            EmitRegisterHelper(builder, indent);

            CloseContextDeclaration(builder, contextSymbol, indent);

            return builder.ToString();
        }

        /// <summary>
        /// Writes the namespace, the containing-type chain and the context's own partial declaration,
        /// and returns the indent its members belong at. <see cref="CloseContextDeclaration"/> closes
        /// exactly what this opened.
        /// </summary>
        /// <remarks>
        /// Shared with <see cref="CddlEmitter"/>, which reopens the same user type in a second file.
        /// Both halves have to reopen it identically: a hardcoded <c>public partial class Name</c> is
        /// CS0262 against an internal context, CS0264 against a generic one, and lands a stray
        /// top-level type beside a nested one.
        /// </remarks>
        public static string OpenContextDeclaration(StringBuilder builder, INamedTypeSymbol contextSymbol)
        {
            bool hasNamespace = !contextSymbol.ContainingNamespace.IsGlobalNamespace;
            string indent = hasNamespace ? "    " : string.Empty;

            if (hasNamespace)
            {
                builder.AppendLine($"namespace {contextSymbol.ContainingNamespace.ToDisplayString()}");
                builder.AppendLine("{");
            }

            // A nested context needs every containing type reopened as a partial, or the generated
            // half lands as a top-level type and Configure is never implemented -- which surfaces as
            // CS0534 on the user's own class, naming nothing to do with generators.
            foreach (INamedTypeSymbol container in Containers(contextSymbol))
            {
                builder.AppendLine($"{indent}{Accessibility(container)} partial {Keyword(container)} {NameWithTypeParameters(container)}");
                builder.AppendLine($"{indent}{{");
                indent += "    ";
            }

            // The declared accessibility, not a hardcoded `public`: a partial declaration whose parts
            // disagree is CS0262.
            builder.AppendLine($"{indent}{Accessibility(contextSymbol)} partial class {NameWithTypeParameters(contextSymbol)}");
            builder.AppendLine($"{indent}{{");

            return indent;
        }

        /// <summary>
        /// Closes the braces <see cref="OpenContextDeclaration"/> opened, given the indent it returned.
        /// </summary>
        public static void CloseContextDeclaration(StringBuilder builder, INamedTypeSymbol contextSymbol, string indent)
        {
            builder.AppendLine($"{indent}}}");

            for (int i = Containers(contextSymbol).Count - 1; i >= 0; i--)
            {
                indent = indent.Substring(4);
                builder.AppendLine($"{indent}}}");
            }

            if (!contextSymbol.ContainingNamespace.IsGlobalNamespace)
            {
                builder.AppendLine("}");
            }
        }

        /// <summary>
        /// The containing-type chain, outermost first.
        /// </summary>
        private static List<INamedTypeSymbol> Containers(INamedTypeSymbol contextSymbol)
        {
            List<INamedTypeSymbol> containers = new List<INamedTypeSymbol>();

            for (INamedTypeSymbol? container = contextSymbol.ContainingType;
                 container is not null;
                 container = container.ContainingType)
            {
                containers.Insert(0, container);
            }

            return containers;
        }

        /// <summary>
        /// Hint name unique across the compilation. Keying on the simple name alone makes two
        /// same-named contexts in different namespaces collide, and the generator throws.
        /// </summary>
        public static string HintName(INamedTypeSymbol contextSymbol)
        {
            return TypeNames.HintNameStem(contextSymbol) + ".CborContext.g.cs";
        }

        private static string Accessibility(INamedTypeSymbol symbol)
        {
            return symbol.DeclaredAccessibility switch
            {
                Microsoft.CodeAnalysis.Accessibility.Public => "public",
                Microsoft.CodeAnalysis.Accessibility.Internal => "internal",
                Microsoft.CodeAnalysis.Accessibility.Protected => "protected",
                Microsoft.CodeAnalysis.Accessibility.ProtectedOrInternal => "protected internal",
                Microsoft.CodeAnalysis.Accessibility.ProtectedAndInternal => "private protected",
                Microsoft.CodeAnalysis.Accessibility.Private => "private",
                _ => "internal",
            };
        }

        private static string Keyword(INamedTypeSymbol symbol)
        {
            return symbol.TypeKind switch
            {
                Microsoft.CodeAnalysis.TypeKind.Struct => symbol.IsRecord ? "record struct" : "struct",
                Microsoft.CodeAnalysis.TypeKind.Interface => "interface",
                _ => symbol.IsRecord ? "record" : "class",
            };
        }

        /// <summary>
        /// A generic container has to be reopened with its type parameters, or the partial does not
        /// match the user's declaration.
        /// </summary>
        private static string NameWithTypeParameters(INamedTypeSymbol symbol)
        {
            return symbol.TypeParameters.Length == 0
                ? symbol.Name
                : $"{symbol.Name}<{string.Join(", ", symbol.TypeParameters.Select(parameter => parameter.Name))}>";
        }

        /// <summary>
        /// One cached accessor per declared root, so callers reach a converter without a dictionary
        /// lookup on the hot path.
        /// </summary>
        private static void EmitTypedAccessors(
            StringBuilder builder,
            string indent,
            IReadOnlyList<TypeModel> ordered,
            IReadOnlyList<ITypeSymbol> roots)
        {
            HashSet<string> rootKeys = new HashSet<string>(
                roots.Select(r => r.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)));

            // Two roots with the same simple name in different namespaces would otherwise emit two
            // members with the same identifier, which is CS0102 on the user's own context.
            HashSet<string> usedAccessorNames = new HashSet<string>(StringComparer.Ordinal);

            foreach (TypeModel model in ordered)
            {
                string key = model.Symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

                if (!rootKeys.Contains(key) || model.Kind == TypeKind.Unsupported)
                {
                    continue;
                }

                string fullName = FullName(model.Symbol);
                string accessorName = UniqueAccessorName(model.Symbol, usedAccessorNames);
                string fieldName = "_" + char.ToLowerInvariant(accessorName[0]) + accessorName.Substring(1);

                builder.AppendLine($"{indent}    private ICborConverter<{fullName}>? {fieldName};");
                builder.AppendLine();
                builder.AppendLine($"{indent}    /// <summary>Converter for <see cref=\"{XmlName(fullName)}\"/>.</summary>");
                builder.AppendLine($"{indent}    public ICborConverter<{fullName}> {accessorName}");
                builder.AppendLine($"{indent}        => {fieldName} ??= GetConverter<{fullName}>();");
                builder.AppendLine();
            }
        }

        private static void EmitConfigure(
            StringBuilder builder,
            string indent,
            GenerationOptions options,
            IReadOnlyList<TypeModel> ordered)
        {
            builder.AppendLine($"{indent}    /// <summary>");
            builder.AppendLine($"{indent}    /// Registers every reachable type. Emitted in dependency order: converters resolve their");
            builder.AppendLine($"{indent}    /// member and element converters as they are constructed, so a dependency must already be");
            builder.AppendLine($"{indent}    /// registered by the time its dependent is built.");
            builder.AppendLine($"{indent}    /// </summary>");
            builder.AppendLine($"{indent}    protected override void Configure(CborOptions options)");
            builder.AppendLine($"{indent}    {{");
            builder.AppendLine($"{indent}        CborConverterRegistry converters = options.Registry.ConverterRegistry;");
            builder.AppendLine();

            EmitOptionAssignments(builder, indent, options);

            foreach (TypeModel model in ordered)
            {
                switch (model.Kind)
                {
                    case TypeKind.Primitive:
                    case TypeKind.Unsupported:
                        // Primitives resolve to concrete converters with no generic instantiation, so
                        // they need no registration. Unsupported types already produced a diagnostic.
                        continue;

                    case TypeKind.Enum:
                        EmitSimpleRegistration(builder, indent, model.Symbol,
                            $"new EnumConverter<{FullName(model.Symbol)}>(options)");
                        break;

                    case TypeKind.Nullable:
                        EmitSimpleRegistration(builder, indent, model.Symbol,
                            $"new NullableConverter<{FullName(model.UnderlyingType!)}>(options)");
                        break;

                    case TypeKind.ByteArray:
                        EmitSimpleRegistration(builder, indent, model.Symbol, "new ByteArrayConverter()");
                        break;

                    case TypeKind.Array:
                        // TypedArrayConverter<T> derives from ArrayConverter<T> and falls back to the
                        // ordinary per-element encoding whenever no typed array tag is present or
                        // TypedArrayMode is Never, so registering it unconditionally for eligible
                        // element types reproduces the reflection provider chain in every mode.
                        EmitSimpleRegistration(builder, indent, model.Symbol,
                            model.IsTypedArray
                                ? $"new TypedArrayConverter<{FullName(model.ElementType!)}>(options)"
                                : $"new ArrayConverter<{FullName(model.ElementType!)}>(options)");
                        break;

                    case TypeKind.Collection:
                        EmitSimpleRegistration(builder, indent, model.Symbol,
                            $"new CollectionConverter<{FullName(model.Symbol)}, {FullName(model.ElementType!)}>(options)");
                        break;

                    case TypeKind.Dictionary:
                        EmitSimpleRegistration(builder, indent, model.Symbol,
                            $"new DictionaryConverter<{FullName(model.Symbol)}, {FullName(model.ElementType!)}, {FullName(model.ValueType!)}>(options)");
                        break;

                    // One converter per arity, named with the tuple's own type arguments -- so the
                    // instantiation is written out here rather than made at run time, which is the whole
                    // point: the reflection provider reaches MakeGenericType, and a tuple was therefore
                    // the one shape a generated context had to refuse.
                    //
                    // The eighth argument is the Rest rather than an eighth element, and Tuple8Converter
                    // recurses into it. The Rest is registered too, by its own model, which the
                    // dependency ordering puts first.
                    case TypeKind.Tuple:
                        EmitSimpleRegistration(builder, indent, model.Symbol,
                            $"new Tuple{model.TupleArguments.Count}Converter<"
                                + string.Join(", ", model.TupleArguments.Select(FullName))
                                + ">(options)");
                        break;

                    case TypeKind.Object:
                        EmitObjectRegistration(builder, indent, model);
                        break;
                }
            }

            builder.AppendLine($"{indent}    }}");
        }

        private static void EmitOptionAssignments(StringBuilder builder, string indent, GenerationOptions options)
        {
            bool wrote = false;

            // A context does not disable the reflection fallback, so a type it does not declare is
            // still mapped by DefaultObjectMappingConvention -- which reads this. Leaving it unset
            // gave one document two naming conventions: declared types converted, fallback types
            // under their declared member names.
            if (options.NamingConvention is not null)
            {
                builder.AppendLine(
                    $"{indent}        options.DefaultNamingConvention = "
                    + $"new global::Dahomey.Cbor.Serialization.Conventions.{options.NamingConvention}();");
                wrote = true;
            }

            if (options.ObjectFormat != "StringKeyMap")
            {
                builder.AppendLine($"{indent}        options.ObjectFormat = CborObjectFormat.{options.ObjectFormat};");
                wrote = true;
            }

            if (options.DiscriminatorPolicy is not null)
            {
                builder.AppendLine($"{indent}        options.DiscriminatorPolicy = CborDiscriminatorPolicy.{options.DiscriminatorPolicy};");
                wrote = true;
            }

            if (options.DiscriminatorSemanticTag is not null)
            {
                builder.AppendLine($"{indent}        options.DiscriminatorSemanticTag = {options.DiscriminatorSemanticTag}UL;");
                wrote = true;
            }

            if (options.MaxDepth is not null)
            {
                builder.AppendLine($"{indent}        options.MaxDepth = {options.MaxDepth};");
                wrote = true;
            }

            if (options.EnumFormat is not null)
            {
                builder.AppendLine($"{indent}        options.EnumFormat = ValueFormat.{options.EnumFormat};");
                wrote = true;
            }

            if (options.DateTimeFormat is not null)
            {
                builder.AppendLine($"{indent}        options.DateTimeFormat = DateTimeFormat.{options.DateTimeFormat};");
                wrote = true;
            }

            // Order-independent, like every assignment above it: TypedArrayMode is a plain setting that
            // no other option constrains, and none of these three reads another's value.
            if (options.TypedArrayMode is not null)
            {
                builder.AppendLine($"{indent}        options.TypedArrayMode = TypedArrayMode.{options.TypedArrayMode};");
                wrote = true;
            }

            if (options.DecimalFormat is not null)
            {
                builder.AppendLine($"{indent}        options.DecimalFormat = DecimalFormat.{options.DecimalFormat};");
                wrote = true;
            }

            if (wrote)
            {
                builder.AppendLine();
            }
        }

        /// <summary>
        /// The registration helper every emitted registration goes through, so that a refused
        /// registration is an exception rather than nothing at all.
        /// </summary>
        private static void EmitRegisterHelper(StringBuilder builder, string indent)
        {
            builder.AppendLine();
            builder.AppendLine($"{indent}    /// <summary>");
            builder.AppendLine($"{indent}    /// Registers one generated converter, refusing to continue if the registry already had a");
            builder.AppendLine($"{indent}    /// converter for that type.");
            builder.AppendLine($"{indent}    /// </summary>");
            builder.AppendLine($"{indent}    /// <remarks>");
            builder.AppendLine($"{indent}    /// RegisterConverter is TryAdd: an existing entry wins and the argument is dropped. Options");
            builder.AppendLine($"{indent}    /// that have already serialized something carry a converter for every type they touched, so a");
            builder.AppendLine($"{indent}    /// context constructed over them would register nothing, report nothing, and still look");
            builder.AppendLine($"{indent}    /// configured -- with every declared type served by the reflection path this context exists to");
            builder.AppendLine($"{indent}    /// replace, which is the path that fails under Native AOT.");
            builder.AppendLine($"{indent}    /// </remarks>");
            builder.AppendLine($"{indent}    private static void RegisterGeneratedConverter(");
            builder.AppendLine($"{indent}        CborConverterRegistry converters, global::System.Type type, ICborConverter converter)");
            builder.AppendLine($"{indent}    {{");
            builder.AppendLine($"{indent}        if (!converters.RegisterConverter(type, converter))");
            builder.AppendLine($"{indent}        {{");
            builder.AppendLine($"{indent}            throw new CborException(");
            builder.AppendLine($"{indent}                $\"These CborOptions already have a converter for {{type}}, so the generated one was \"");
            builder.AppendLine($"{indent}                + \"refused and the reflection path would be used instead. Construct the context before \"");
            builder.AppendLine($"{indent}                + \"the options are used to read or write, or give it its own CborOptions.\");");
            builder.AppendLine($"{indent}        }}");
            builder.AppendLine($"{indent}    }}");
        }

        private static void EmitSimpleRegistration(
            StringBuilder builder, string indent, ITypeSymbol type, string converterExpression)
        {
            builder.AppendLine($"{indent}        RegisterGeneratedConverter(converters, typeof({FullName(type)}), {converterExpression});");
            builder.AppendLine();
        }

        private static void EmitObjectRegistration(StringBuilder builder, string indent, TypeModel model)
        {
            string fullName = FullName(model.Symbol);

            builder.AppendLine($"{indent}        options.Registry.ObjectMappingRegistry.Register<{fullName}>(objectMapping =>");
            builder.AppendLine($"{indent}        {{");

            if (model.ObjectFormat != "StringKeyMap")
            {
                builder.AppendLine($"{indent}            objectMapping.SetObjectFormat(CborObjectFormat.{model.ObjectFormat});");
            }

            if (model.Members.Count == 0)
            {
                builder.AppendLine($"{indent}            objectMapping.SetMemberMappings(System.Array.Empty<IMemberMapping>());");
            }
            else
            {
                builder.AppendLine($"{indent}            objectMapping.SetMemberMappings(new IMemberMapping[]");
                builder.AppendLine($"{indent}            {{");

                foreach (MemberModel member in model.Members)
                {
                    EmitMemberMapping(builder, indent, model, member);
                }

                builder.AppendLine($"{indent}            }});");
            }

            // SetDiscriminator inserts the discriminator entry at index 0 of the member list, so it
            // must run after SetMemberMappings, which replaces that list wholesale.
            if (model.Discriminator is not null)
            {
                builder.AppendLine($"{indent}            objectMapping.SetDiscriminator({model.Discriminator});");
            }

            if (model.DiscriminatorPolicy is not null)
            {
                builder.AppendLine($"{indent}            objectMapping.SetDiscriminatorPolicy(CborDiscriminatorPolicy.{model.DiscriminatorPolicy});");
            }

            builder.AppendLine($"{indent}        }});");
            builder.AppendLine();

            string factory = model.CanInstantiate ? $", () => new {fullName}()" : string.Empty;
            builder.AppendLine($"{indent}        RegisterGeneratedConverter(");
            builder.AppendLine($"{indent}            converters, typeof({fullName}), new ObjectConverter<{fullName}>(options{factory}));");
            builder.AppendLine();
        }

        private static void EmitMemberMapping(
            StringBuilder builder, string indent, TypeModel model, MemberModel member)
        {
            string ownerName = FullName(model.Symbol);
            string memberTypeName = MemberTypeName(member.Type);

            bool isStruct = model.Symbol.TypeKind == Microsoft.CodeAnalysis.TypeKind.Struct;
            string mappingType = isStruct
                ? $"DelegateStructMemberMapping<{ownerName}, {memberTypeName}>"
                : $"DelegateMemberMapping<{ownerName}, {memberTypeName}>";

            // Structs need ref-taking accessors so mutations are not lost on a copy.
            string getter = isStruct
                ? $"(ref {ownerName} o) => o.{member.Name}"
                : $"o => o.{member.Name}";

            string setter = member.CanWrite
                ? isStruct
                    ? $"(ref {ownerName} o, {memberTypeName} v) => o.{member.Name} = v"
                    : $"(o, v) => o.{member.Name} = v"
                : "null";

            string key = member.CborIndex is not null
                ? $".SetMemberIndex({member.CborIndex})"
                : $".SetMemberName({Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(member.CborName, quote: true)})";

            // Both are calls DelegateMemberMapping has always offered; what was missing was the
            // generator making them, which is why they were CBOR1007 rather than a shape it could not
            // reproduce. Order follows the reflection path's: the predicate, then the requirement.
            string shouldSerialize = member.ShouldSerializeMethod is null
                ? string.Empty
                : $".SetShouldSerializeMethod(o => (({ownerName})o).{member.ShouldSerializeMethod}())";

            string required = member.RequirementPolicy is null
                ? string.Empty
                : $".SetRequired({member.RequirementPolicy})";

            builder.AppendLine($"{indent}                new {mappingType}(");
            builder.AppendLine($"{indent}                    converters,");
            builder.AppendLine($"{indent}                    {getter},");
            builder.AppendLine($"{indent}                    {setter}){key}{shouldSerialize}{required},");
        }

        private static string FullName(ITypeSymbol type)
        {
            return type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        }

        /// <summary>
        /// Like <see cref="FullName"/>, but keeps a <c>string?</c> member's own `?` in the generated
        /// <c>DelegateMemberMapping&lt;TOwner, TMember&gt;</c>. <c>FullyQualifiedFormat</c> omits the
        /// nullable-<em>reference</em> modifier by default; without it, a member the source annotates
        /// <c>Annotated</c> gets a bare (non-nullable) TMember, and the generated file -- which is
        /// unconditionally under <c>#nullable enable</c>, regardless of the declaring file's own
        /// nullable context -- warns CS8603 on the getter lambda returning that member. <c>None</c>
        /// needs no such handling: an unannotated member is exempt from nullable warnings by
        /// construction, in both the declaring file and the generated one. Reference types only: for a
        /// value type, <see cref="NullableAnnotation.Annotated"/> means <c>Nullable&lt;T&gt;</c>
        /// (<c>int?</c>), whose "?" <see cref="FullName"/> already renders as part of the type's own
        /// display string -- adding a second one here would emit the syntax error <c>int??</c>.
        /// </summary>
        private static string MemberTypeName(ITypeSymbol type)
        {
            string name = FullName(type);

            return type.IsReferenceType && type.NullableAnnotation == NullableAnnotation.Annotated
                ? name + "?"
                : name;
        }

        private static string XmlName(string fullName)
        {
            return fullName.Replace("global::", string.Empty).Replace('<', '{').Replace('>', '}');
        }

        /// <summary>
        /// Qualifies with the containing namespace only when the simple name is already taken, so the
        /// common case keeps the short, predictable identifier.
        /// </summary>
        /// <remarks>
        /// Order dependent by construction: which type keeps the short name is decided by which is seen
        /// first. That is correct for accessors, whose names only have to be unique and stable within
        /// one emitted file. CDDL rule names cannot be derived this way -- a schema is compared against
        /// other copies of itself -- so <see cref="TypeNames.BuildRuleNames"/> resolves collisions from
        /// the full type key instead. The two share <see cref="TypeNames.AccessorName"/> as their base.
        /// </remarks>
        private static string UniqueAccessorName(ITypeSymbol type, HashSet<string> used)
        {
            string name = TypeNames.AccessorName(type);

            if (used.Add(name))
            {
                return name;
            }

            string qualified = string.Concat(
                type.ContainingNamespace.ToDisplayString().Split('.').Where(part => part.Length > 0)) + name;

            if (used.Add(qualified))
            {
                return qualified;
            }

            for (int suffix = 2; ; suffix++)
            {
                string candidate = qualified + suffix;

                if (used.Add(candidate))
                {
                    return candidate;
                }
            }
        }

    }
}
