using Microsoft.CodeAnalysis;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Dahomey.Cbor.Generator
{
    /// <summary>
    /// Renders the generated half of a context: the <c>Configure</c> override plus a strongly-typed
    /// converter accessor per declared root type.
    /// </summary>
    internal static class Emitter
    {
        public static string Emit(
            INamedTypeSymbol contextSymbol,
            GenerationOptions options,
            IReadOnlyList<TypeModel> ordered,
            IReadOnlyList<ITypeSymbol> roots)
        {
            StringBuilder builder = new StringBuilder();

            builder.AppendLine("// <auto-generated/>");
            builder.AppendLine("#nullable enable");
            builder.AppendLine();
            builder.AppendLine("using Dahomey.Cbor;");
            builder.AppendLine("using Dahomey.Cbor.Attributes;");
            builder.AppendLine("using Dahomey.Cbor.Serialization;");
            builder.AppendLine("using Dahomey.Cbor.Serialization.Converters;");
            builder.AppendLine("using Dahomey.Cbor.Serialization.Converters.Mappings;");
            builder.AppendLine();

            bool hasNamespace = !contextSymbol.ContainingNamespace.IsGlobalNamespace;
            string indent = hasNamespace ? "    " : string.Empty;

            if (hasNamespace)
            {
                builder.AppendLine($"namespace {contextSymbol.ContainingNamespace.ToDisplayString()}");
                builder.AppendLine("{");
            }

            builder.AppendLine($"{indent}public partial class {contextSymbol.Name}");
            builder.AppendLine($"{indent}{{");

            EmitTypedAccessors(builder, indent, ordered, roots);
            EmitConfigure(builder, indent, options, ordered);

            builder.AppendLine($"{indent}}}");

            if (hasNamespace)
            {
                builder.AppendLine("}");
            }

            return builder.ToString();
        }

        /// <summary>
        /// One cached accessor per declared root, so callers reach a converter without a dictionary
        /// lookup on the hot path.
        /// </summary>
        private static void EmitTypedAccessors(
            StringBuilder builder,
            string indent,
            IReadOnlyList<TypeModel> ordered,
            IReadOnlyList<ITypeSymbol> roots)
        {
            HashSet<string> rootKeys = new HashSet<string>(
                roots.Select(r => r.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)));

            foreach (TypeModel model in ordered)
            {
                string key = model.Symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

                if (!rootKeys.Contains(key) || model.Kind == TypeKind.Unsupported)
                {
                    continue;
                }

                string fullName = FullName(model.Symbol);
                string accessorName = TypeNames.AccessorName(model.Symbol);
                string fieldName = "_" + char.ToLowerInvariant(accessorName[0]) + accessorName.Substring(1);

                builder.AppendLine($"{indent}    private ICborConverter<{fullName}>? {fieldName};");
                builder.AppendLine();
                builder.AppendLine($"{indent}    /// <summary>Converter for <see cref=\"{XmlName(fullName)}\"/>.</summary>");
                builder.AppendLine($"{indent}    public ICborConverter<{fullName}> {accessorName}");
                builder.AppendLine($"{indent}        => {fieldName} ??= GetConverter<{fullName}>();");
                builder.AppendLine();
            }
        }

        private static void EmitConfigure(
            StringBuilder builder,
            string indent,
            GenerationOptions options,
            IReadOnlyList<TypeModel> ordered)
        {
            builder.AppendLine($"{indent}    /// <summary>");
            builder.AppendLine($"{indent}    /// Registers every reachable type. Emitted in dependency order: converters resolve their");
            builder.AppendLine($"{indent}    /// member and element converters as they are constructed, so a dependency must already be");
            builder.AppendLine($"{indent}    /// registered by the time its dependent is built.");
            builder.AppendLine($"{indent}    /// </summary>");
            builder.AppendLine($"{indent}    protected override void Configure(CborOptions options)");
            builder.AppendLine($"{indent}    {{");
            builder.AppendLine($"{indent}        CborConverterRegistry converters = options.Registry.ConverterRegistry;");
            builder.AppendLine();

            EmitOptionAssignments(builder, indent, options);

            foreach (TypeModel model in ordered)
            {
                switch (model.Kind)
                {
                    case TypeKind.Primitive:
                    case TypeKind.Unsupported:
                        // Primitives resolve to concrete converters with no generic instantiation, so
                        // they need no registration. Unsupported types already produced a diagnostic.
                        continue;

                    case TypeKind.Enum:
                        EmitSimpleRegistration(builder, indent, model.Symbol,
                            $"new EnumConverter<{FullName(model.Symbol)}>(options)");
                        break;

                    case TypeKind.Nullable:
                        EmitSimpleRegistration(builder, indent, model.Symbol,
                            $"new NullableConverter<{FullName(model.UnderlyingType!)}>(options)");
                        break;

                    case TypeKind.ByteArray:
                        EmitSimpleRegistration(builder, indent, model.Symbol, "new ByteArrayConverter()");
                        break;

                    case TypeKind.Array:
                        // TypedArrayConverter<T> derives from ArrayConverter<T> and falls back to the
                        // ordinary per-element encoding whenever no typed array tag is present or
                        // TypedArrayMode is Never, so registering it unconditionally for eligible
                        // element types reproduces the reflection provider chain in every mode.
                        EmitSimpleRegistration(builder, indent, model.Symbol,
                            model.IsTypedArray
                                ? $"new TypedArrayConverter<{FullName(model.ElementType!)}>(options)"
                                : $"new ArrayConverter<{FullName(model.ElementType!)}>(options)");
                        break;

                    case TypeKind.Collection:
                        EmitSimpleRegistration(builder, indent, model.Symbol,
                            $"new CollectionConverter<{FullName(model.Symbol)}, {FullName(model.ElementType!)}>(options)");
                        break;

                    case TypeKind.Dictionary:
                        EmitSimpleRegistration(builder, indent, model.Symbol,
                            $"new DictionaryConverter<{FullName(model.Symbol)}, {FullName(model.ElementType!)}, {FullName(model.ValueType!)}>(options)");
                        break;

                    case TypeKind.Object:
                        EmitObjectRegistration(builder, indent, model);
                        break;
                }
            }

            builder.AppendLine($"{indent}    }}");
        }

        private static void EmitOptionAssignments(StringBuilder builder, string indent, GenerationOptions options)
        {
            bool wrote = false;

            if (options.ObjectFormat != "StringKeyMap")
            {
                builder.AppendLine($"{indent}        options.ObjectFormat = CborObjectFormat.{options.ObjectFormat};");
                wrote = true;
            }

            if (options.DiscriminatorPolicy is not null)
            {
                builder.AppendLine($"{indent}        options.DiscriminatorPolicy = CborDiscriminatorPolicy.{options.DiscriminatorPolicy};");
                wrote = true;
            }

            if (options.DiscriminatorSemanticTag is not null)
            {
                builder.AppendLine($"{indent}        options.DiscriminatorSemanticTag = {options.DiscriminatorSemanticTag}UL;");
                wrote = true;
            }

            if (options.MaxDepth is not null)
            {
                builder.AppendLine($"{indent}        options.MaxDepth = {options.MaxDepth};");
                wrote = true;
            }

            if (options.EnumFormat is not null)
            {
                builder.AppendLine($"{indent}        options.EnumFormat = ValueFormat.{options.EnumFormat};");
                wrote = true;
            }

            if (options.DateTimeFormat is not null)
            {
                builder.AppendLine($"{indent}        options.DateTimeFormat = DateTimeFormat.{options.DateTimeFormat};");
                wrote = true;
            }

            // Assigned last: CborOptions.Deterministic forces TypedArrayMode to LittleEndian, and the
            // TypedArrayMode setter refuses any other value while Deterministic is set. Writing this
            // after every other assignment keeps the pair consistent whichever the user declared.
            if (options.TypedArrayMode is not null)
            {
                builder.AppendLine($"{indent}        options.TypedArrayMode = TypedArrayMode.{options.TypedArrayMode};");
                wrote = true;
            }

            if (wrote)
            {
                builder.AppendLine();
            }
        }

        private static void EmitSimpleRegistration(
            StringBuilder builder, string indent, ITypeSymbol type, string converterExpression)
        {
            builder.AppendLine($"{indent}        converters.RegisterConverter(typeof({FullName(type)}), {converterExpression});");
            builder.AppendLine();
        }

        private static void EmitObjectRegistration(StringBuilder builder, string indent, TypeModel model)
        {
            string fullName = FullName(model.Symbol);

            builder.AppendLine($"{indent}        options.Registry.ObjectMappingRegistry.Register<{fullName}>(objectMapping =>");
            builder.AppendLine($"{indent}        {{");

            if (model.ObjectFormat != "StringKeyMap")
            {
                builder.AppendLine($"{indent}            objectMapping.SetObjectFormat(CborObjectFormat.{model.ObjectFormat});");
            }

            if (model.Members.Count == 0)
            {
                builder.AppendLine($"{indent}            objectMapping.SetMemberMappings(System.Array.Empty<IMemberMapping>());");
            }
            else
            {
                builder.AppendLine($"{indent}            objectMapping.SetMemberMappings(new IMemberMapping[]");
                builder.AppendLine($"{indent}            {{");

                foreach (MemberModel member in model.Members)
                {
                    EmitMemberMapping(builder, indent, model, member);
                }

                builder.AppendLine($"{indent}            }});");
            }

            // SetDiscriminator inserts the discriminator entry at index 0 of the member list, so it
            // must run after SetMemberMappings, which replaces that list wholesale.
            if (model.Discriminator is not null)
            {
                builder.AppendLine($"{indent}            objectMapping.SetDiscriminator({model.Discriminator});");
            }

            if (model.DiscriminatorPolicy is not null)
            {
                builder.AppendLine($"{indent}            objectMapping.SetDiscriminatorPolicy(CborDiscriminatorPolicy.{model.DiscriminatorPolicy});");
            }

            builder.AppendLine($"{indent}        }});");
            builder.AppendLine();

            string factory = model.CanInstantiate ? $", () => new {fullName}()" : string.Empty;
            builder.AppendLine($"{indent}        converters.RegisterConverter(");
            builder.AppendLine($"{indent}            typeof({fullName}), new ObjectConverter<{fullName}>(options{factory}));");
            builder.AppendLine();
        }

        private static void EmitMemberMapping(
            StringBuilder builder, string indent, TypeModel model, MemberModel member)
        {
            string ownerName = FullName(model.Symbol);
            string memberTypeName = MemberTypeName(member.Type);

            bool isStruct = model.Symbol.TypeKind == Microsoft.CodeAnalysis.TypeKind.Struct;
            string mappingType = isStruct
                ? $"DelegateStructMemberMapping<{ownerName}, {memberTypeName}>"
                : $"DelegateMemberMapping<{ownerName}, {memberTypeName}>";

            // Structs need ref-taking accessors so mutations are not lost on a copy.
            string getter = isStruct
                ? $"(ref {ownerName} o) => o.{member.Name}"
                : $"o => o.{member.Name}";

            string setter = member.CanWrite
                ? isStruct
                    ? $"(ref {ownerName} o, {memberTypeName} v) => o.{member.Name} = v"
                    : $"(o, v) => o.{member.Name} = v"
                : "null";

            string key = member.CborIndex is not null
                ? $".SetMemberIndex({member.CborIndex})"
                : $".SetMemberName({Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(member.CborName, quote: true)})";

            builder.AppendLine($"{indent}                new {mappingType}(");
            builder.AppendLine($"{indent}                    converters,");
            builder.AppendLine($"{indent}                    {getter},");
            builder.AppendLine($"{indent}                    {setter}){key},");
        }

        private static string FullName(ITypeSymbol type)
        {
            return type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        }

        /// <summary>
        /// Like <see cref="FullName"/>, but keeps a <c>string?</c> member's own `?` in the generated
        /// <c>DelegateMemberMapping&lt;TOwner, TMember&gt;</c>. <c>FullyQualifiedFormat</c> omits the
        /// nullable-*reference* modifier by default; without it, a member the source annotates
        /// <c>Annotated</c> gets a bare (non-nullable) TMember, and the generated file -- which is
        /// unconditionally under `#nullable enable`, regardless of the declaring file's own nullable
        /// context -- warns CS8603 on the getter lambda returning that member. `None` needs no such
        /// handling: an unannotated member is exempt from nullable warnings by construction, in both
        /// the declaring file and the generated one. Reference types only: for a value type,
        /// <c>NullableAnnotation.Annotated</c> means <c>Nullable&lt;T&gt;</c> (<c>int?</c>), whose "?"
        /// <see cref="FullName"/> already renders as part of the type's own display string -- adding a
        /// second one here would emit the syntax error <c>int??</c>.
        /// </summary>
        private static string MemberTypeName(ITypeSymbol type)
        {
            string name = FullName(type);
            return type.IsReferenceType && type.NullableAnnotation == NullableAnnotation.Annotated
                ? name + "?"
                : name;
        }

        private static string XmlName(string fullName)
        {
            return fullName.Replace("global::", string.Empty).Replace('<', '{').Replace('>', '}');
        }
    }
}
