using Dahomey.Cbor.Attributes;
using Dahomey.Cbor.Serialization;
using System;
using System.Collections.Generic;
using System.Numerics;
using Xunit;

namespace Dahomey.Cbor.Tests
{
    public class GeneratedFractionHolder
    {
        public CborDecimalFraction Price { get; set; }
        public CborBigFloat Scale { get; set; }
        public CborDecimalFraction? Optional { get; set; }
    }

    /// <summary>
    /// Exercises the source-generated path, which is the half a run-time test cannot reach.
    /// </summary>
    /// <remarks>
    /// The regression this guards is silent. Both types are non-generic structs, so without an entry in
    /// <c>TypeCollector.IsPrimitive</c> they are not classified unsupported -- <c>Classify</c> falls
    /// through to <c>TypeKind.Object</c>, the build succeeds, and the emitted context writes
    /// <c>Mantissa</c> and <c>Exponent</c> as a map behind CBOR1006 warnings. Green build, wrong bytes.
    /// What catches it is <see cref="FractionTypeTests.GeneratedContextRoundTrip"/> and the
    /// <c>GeneratedCorpusTests</c> cases, which compare the generated bytes against the reflection
    /// path's.
    /// </remarks>
    [CborSerializable(typeof(GeneratedFractionHolder))]
    public partial class FractionContext : CborSerializerContext
    {
    }

    /// <summary>
    /// The two RFC 8949 §3.4.4 types, <see cref="CborDecimalFraction"/> (tag 4) and
    /// <see cref="CborBigFloat"/> (tag 5). The hex buffers for <c>273.15</c> and <c>1.5</c> are the ones
    /// §3.4.4 spells out.
    /// </summary>
    /// <remarks>
    /// <c>DecimalFractionTests</c> is the neighbouring file and covers the other half of tag 4: what a
    /// member typed <see cref="decimal"/> writes under <c>CborOptions.DecimalFormat</c> and reads back.
    /// The two agree on the bytes and differ in what they can hold, which
    /// <see cref="ADecimalMemberAndAFractionMemberWriteTheSameBytes"/> pins.
    /// </remarks>
    public class FractionTypeTests
    {
        public class ObjectWithFractions
        {
            [CborProperty("p")]
            public CborDecimalFraction Price { get; set; }

            [CborProperty("s")]
            public CborBigFloat Scale { get; set; }
        }

        [Theory]
        [InlineData("C48221196AB3", "27315", -2)]      // 273.15, RFC 8949 section 3.4.4
        [InlineData("C4820000", "0", 0)]
        [InlineData("C482000A", "10", 0)]
        [InlineData("C4820101", "1", 1)]
        [InlineData("C48220182D", "45", -1)]                         // 4.5
        [InlineData("C482002B", "-12", 0)]
        [InlineData("C48221C249010000000000000000", "18446744073709551616", -2)]
        public void ReadDecimalFraction(string hexBuffer, string mantissa, int exponent)
        {
            Helper.TestRead(hexBuffer, new CborDecimalFraction(BigInteger.Parse(mantissa), exponent));
        }

        [Theory]
        [InlineData("C5822003", "3", -1)]              // 1.5, RFC 8949 section 3.4.4
        [InlineData("C5820000", "0", 0)]
        [InlineData("C58200C249010000000000000000", "18446744073709551616", 0)]
        public void ReadBigFloat(string hexBuffer, string mantissa, int exponent)
        {
            Helper.TestRead(hexBuffer, new CborBigFloat(BigInteger.Parse(mantissa), exponent));
        }

        [Theory]
        [InlineData("27315", -2, "C48221196AB3")]
        [InlineData("0", 0, "C4820000")]
        [InlineData("-12", 0, "C482002B")]
        // Past a basic integer, so the mantissa takes a bignum tag of its own -- which is
        // WriteBigInteger's decision, not this writer's, and is what section 3.4.4 permits.
        [InlineData("18446744073709551616", -1, "C48220C249010000000000000000")]
        [InlineData("79228162514264337593543950335", 0, "C48200C24CFFFFFFFFFFFFFFFFFFFFFFFF")]
        public void WriteDecimalFraction(string mantissa, int exponent, string expectedHexBuffer)
        {
            Helper.TestWrite(new CborDecimalFraction(BigInteger.Parse(mantissa), exponent), expectedHexBuffer);
        }

        [Theory]
        [InlineData("3", -1, "C5822003")]
        [InlineData("1", 96, "C582186001")]
        public void WriteBigFloat(string mantissa, int exponent, string expectedHexBuffer)
        {
            Helper.TestWrite(new CborBigFloat(BigInteger.Parse(mantissa), exponent), expectedHexBuffer);
        }

        /// <summary>
        /// A document is re-emitted as it arrived, mantissa and exponent untouched. Two encodings of ten
        /// stay two encodings of ten: normalising would make the type lossy in the way mapping onto
        /// <see cref="decimal"/> would.
        /// </summary>
        [Theory]
        [InlineData("C482000A")]
        [InlineData("C4820101")]
        [InlineData("C48221196AB3")]
        public void ANonNormalisedValueRoundTripsUnchanged(string hexBuffer)
        {
            Assert.Equal(hexBuffer, Helper.Write(Helper.Read<CborDecimalFraction>(hexBuffer)),
                ignoreCase: true);
        }

        [Fact]
        public void ABigFloatRoundTripsUnchanged()
        {
            Assert.Equal("C5822003", Helper.Write(Helper.Read<CborBigFloat>("C5822003")), ignoreCase: true);
        }

        /// <summary>
        /// The tag is required: it is the only thing separating either value from the plain two-element
        /// array it is encoded as, and the innermost of tags 4 and 5 decides, so the other kind is
        /// refused rather than reinterpreted.
        /// </summary>
        [Theory]
        [InlineData("8221196AB3")]              // no tag at all
        [InlineData("C5822003")]                // tag 5 read as a decimal fraction
        [InlineData("C4C58221196AB3")]          // innermost is tag 5
        [InlineData("C1C58221196AB3")]          // foreign tag over tag 5
        public void ADecimalFractionNeedsTagFour(string hexBuffer)
        {
            Assert.Throws<CborException>(() => Helper.Read<CborDecimalFraction>(hexBuffer));
        }

        /// <summary>
        /// The whole tag stack is read, as everywhere since #183, so a value under an outer tag is not
        /// the one shape this reader alone refuses. A foreign tag between tag 4 and its content array is
        /// skipped for the same reason it is skipped anywhere else.
        /// </summary>
        [Theory]
        [InlineData("C1C48221196AB3")]          // foreign tag over tag 4
        [InlineData("C4C18221196AB3")]          // foreign tag under tag 4
        [InlineData("C5C48221196AB3")]          // tag 5 outside, tag 4 nearest the data
        [InlineData("C48221C1196AB3")]          // foreign tag on the mantissa
        public void ADecimalFractionIsReadThroughTheTagStack(string hexBuffer)
        {
            Helper.TestRead(hexBuffer, new CborDecimalFraction(27315, -2));
        }

        /// <summary>
        /// An indefinite-length content array is accepted -- §3.4.4 does not forbid one, and the reader
        /// is lenient about indefinite lengths everywhere else -- but it still has to hold exactly two
        /// items, and the break has to be consumed or the item after it reads as part of this one.
        /// </summary>
        [Fact]
        public void AnIndefiniteLengthContentArrayIsRead()
        {
            Helper.TestRead("C49F21196AB3FF", new CborDecimalFraction(27315, -2));
        }

        [Fact]
        public void AnIndefiniteLengthContentArrayLeavesNothingBehind()
        {
            List<CborDecimalFraction> read = Helper.Read<List<CborDecimalFraction>>(
                "82C49F21196AB3FFC49F2003FF");

            Assert.Equal(new CborDecimalFraction(27315, -2), read[0]);
            Assert.Equal(new CborDecimalFraction(3, -1), read[1]);
        }

        [Theory]
        [InlineData("C483211903E800")]          // three items
        [InlineData("C48121")]                  // one item
        [InlineData("C48021196AB3")]            // empty, then two stray items
        [InlineData("C49FFF")]                  // indefinite, empty
        [InlineData("C49F21FF")]                // indefinite, one item
        [InlineData("C49F21196AB300FF")]        // indefinite, three items
        [InlineData("C40C")]                    // not an array at all
        public void AContentArrayOfAnyOtherLengthIsRefused(string hexBuffer)
        {
            Assert.Throws<CborException>(() => Helper.Read<CborDecimalFraction>(hexBuffer));
        }

        /// <summary>
        /// §3.4.4 requires the exponent to be a basic integer, which is what reading it as an
        /// <see cref="int"/> enforces -- a bignum-tagged exponent is a byte string and fails on major
        /// type. The <see cref="int"/> itself is a narrowing of the format, which permits major type 0
        /// or 1 and so reaches ±2^64: a conforming document beyond ±2^31 is refused rather than read.
        /// </summary>
        [Theory]
        [InlineData("C4821B000000010000000001")]    // exponent 2^32
        [InlineData("C4823B000000010000000001")]    // exponent -2^32 - 1
        [InlineData("C482C2410101")]                // exponent as a tagged bignum
        [InlineData("C482614101")]                  // exponent as a text string
        public void AnExponentOutsideInt32IsRefused(string hexBuffer)
        {
            Assert.Throws<CborException>(() => Helper.Read<CborDecimalFraction>(hexBuffer));
        }

        /// <summary>
        /// Equality is structural over the pair as encoded, so two encodings of one number are not
        /// equal. Stated and pinned because it decides behaviour as a dictionary key and under
        /// <c>Deterministic</c>, where they sort as the different byte strings they are.
        /// </summary>
        [Fact]
        public void TwoEncodingsOfOneNumberAreNotEqual()
        {
            CborDecimalFraction ten = new CborDecimalFraction(10, 0);
            CborDecimalFraction alsoTen = new CborDecimalFraction(1, 1);

            Assert.NotEqual(ten, alsoTen);
            Assert.False(ten == alsoTen);
            Assert.Equal(ten.ToDecimal(), alsoTen.ToDecimal());
            Assert.Equal(new CborDecimalFraction(10, 0), ten);
            Assert.Equal(new CborDecimalFraction(10, 0).GetHashCode(), ten.GetHashCode());
        }

        [Fact]
        public void ADecimalFractionIsExactlyADecimalWhereThereIsOne()
        {
            Assert.Equal(273.15m, new CborDecimalFraction(27315, -2).ToDecimal());
            Assert.Equal(0m, new CborDecimalFraction(0, 5).ToDecimal());
            Assert.Equal(-12m, new CborDecimalFraction(-12, 0).ToDecimal());
            Assert.Equal(1000m, new CborDecimalFraction(1, 3).ToDecimal());
            Assert.Equal(
                79228162514264337593543950335m,
                new CborDecimalFraction(BigInteger.Parse("79228162514264337593543950335"), 0).ToDecimal());
        }

        /// <summary>
        /// An exponent below -28 is not by itself fatal: a mantissa with trailing zeros gives the scale
        /// back, so <c>1000e-30</c> is the representable <c>1e-27</c>.
        /// </summary>
        [Fact]
        public void AScaleThatReducesToTwentyEightIsRepresentable()
        {
            Assert.Equal(1e-27m, new CborDecimalFraction(1000, -30).ToDecimal());
        }

        [Theory]
        [InlineData("3", -29)]                                      // scale will not reduce
        [InlineData("1", 29)]                                       // past decimal.MaxValue
        [InlineData("79228162514264337593543950336", 0)]            // mantissa wider than 96 bits
        public void ADecimalFractionWithNoDecimalThrowsRatherThanRounding(string mantissa, int exponent)
        {
            CborDecimalFraction value = new CborDecimalFraction(BigInteger.Parse(mantissa), exponent);

            Assert.Throws<OverflowException>(() => value.ToDecimal());
        }

        [Fact]
        public void ADecimalFractionConvertsToTheNearestDouble()
        {
            Assert.Equal(273.15, new CborDecimalFraction(27315, -2).ToDouble());
            Assert.Equal(0.1, new CborDecimalFraction(1, -1).ToDouble());
            Assert.Equal(0.0, new CborDecimalFraction(1, -400).ToDouble());
            Assert.Throws<OverflowException>(() => new CborDecimalFraction(1, 400).ToDouble());
        }

        /// <summary>
        /// Exact, which is worth pinning because it looks as though it could not be: a
        /// <see cref="double"/> is <c>m × 2^e</c> and <c>2^-n = 5^n × 10^-n</c>, so <c>0.1</c> lands as
        /// its true value rather than as <c>1e-1</c>.
        /// </summary>
        [Fact]
        public void ADoubleConvertsExactlyToBothTypes()
        {
            Assert.Equal(new CborBigFloat(3602879701896397, -55), (CborBigFloat)0.1);
            Assert.Equal(new CborBigFloat(3, -1), (CborBigFloat)1.5);

            CborDecimalFraction tenth = (CborDecimalFraction)0.1;

            Assert.Equal(-55, tenth.Exponent);
            Assert.Equal(3602879701896397 * BigInteger.Pow(5, 55), tenth.Mantissa);
            Assert.Equal(0.1, tenth.ToDouble());
        }

        [Fact]
        public void ADecimalConvertsExactlyToADecimalFraction()
        {
            Assert.Equal(new CborDecimalFraction(27315, -2), (CborDecimalFraction)273.15m);
            Assert.Equal(new CborDecimalFraction(0, -2), (CborDecimalFraction)0.00m);
            Assert.Equal(new CborDecimalFraction(-27315, -2), (CborDecimalFraction)(-273.15m));
        }

        /// <summary>
        /// There is no conversion from <see cref="decimal"/> to <see cref="CborBigFloat"/>, and its
        /// absence is a decision: it cannot be exact, because <c>m × 2^e = 1/10</c> has no integer
        /// solution. Asserted rather than left to the comment, since adding the operator would compile
        /// and would silently round.
        /// </summary>
        [Fact]
        public void ThereIsNoConversionFromDecimalToABigFloat()
        {
            foreach (System.Reflection.MethodInfo method in typeof(CborBigFloat).GetMethods())
            {
                if (method.Name == "op_Explicit" || method.Name == "op_Implicit")
                {
                    Assert.NotEqual(typeof(decimal), Assert.Single(method.GetParameters()).ParameterType);
                }
            }
        }

        [Theory]
        [InlineData(double.NaN)]
        [InlineData(double.PositiveInfinity)]
        [InlineData(double.NegativeInfinity)]
        public void ADoubleWithNoFiniteValueHasNoFraction(double value)
        {
            Assert.Throws<OverflowException>(() => (CborDecimalFraction)value);
            Assert.Throws<OverflowException>(() => (CborBigFloat)value);
        }

        /// <summary>
        /// Factors of two come out of the mantissa first, so a large negative exponent does not by
        /// itself put a value out of reach: <c>2^100 × 2^-100</c> is one.
        /// </summary>
        [Fact]
        public void ABigFloatIsExactlyADecimalWhereThereIsOne()
        {
            Assert.Equal(1.5m, new CborBigFloat(3, -1).ToDecimal());
            Assert.Equal(0m, new CborBigFloat(0, -1000).ToDecimal());
            Assert.Equal(1m, new CborBigFloat(BigInteger.Pow(2, 100), -100).ToDecimal());
            Assert.Equal(1.5, new CborBigFloat(3, -1).ToDouble());
        }

        /// <summary>
        /// <c>0.1</c> as a <see cref="double"/> is a bigfloat with an odd mantissa over 2^55, and no
        /// <see cref="decimal"/> has that value -- the scale it needs is 55, not 28. So the exact
        /// conversion refuses rather than handing back <c>0.1m</c>, which is a different number.
        /// </summary>
        [Fact]
        public void ABigFloatWithNoDecimalThrowsRatherThanRounding()
        {
            Assert.Throws<OverflowException>(() => ((CborBigFloat)0.1).ToDecimal());
            Assert.Equal(0.1, ((CborBigFloat)0.1).ToDouble());
        }

        [Fact]
        public void ABigFloatOutsideDoubleIsRefusedRatherThanInfinite()
        {
            Assert.Throws<OverflowException>(() => new CborBigFloat(1, 2000).ToDouble());
            Assert.Equal(0.0, new CborBigFloat(1, -2000).ToDouble());
        }

        [Fact]
        public void ReadObject()
        {
            ObjectWithFractions obj = Helper.Read<ObjectWithFractions>("A26170C48221196AB36173C5822003");

            Assert.Equal(new CborDecimalFraction(27315, -2), obj.Price);
            Assert.Equal(new CborBigFloat(3, -1), obj.Scale);
        }

        [Fact]
        public void WriteObject()
        {
            ObjectWithFractions obj = new ObjectWithFractions
            {
                Price = new CborDecimalFraction(27315, -2),
                Scale = new CborBigFloat(3, -1),
            };

            Helper.TestWrite(obj, "A26170C48221196AB36173C5822003");
        }

        /// <summary>
        /// The shape that failed for <see cref="BigInteger"/>: <c>NullableConverter</c> skips a semantic
        /// tag before looking for null, which loses the tag for a converter that dispatches on one. The
        /// bookmark path it took to fix that has to hold here too, since both of these dispatch on a tag.
        /// </summary>
        [Theory]
        [InlineData("C48221196AB3", "27315", -2)]
        [InlineData("C1C48221196AB3", "27315", -2)]
        public void ReadNullable(string hexBuffer, string mantissa, int exponent)
        {
            CborDecimalFraction? value = Helper.Read<CborDecimalFraction?>(hexBuffer);

            Assert.Equal(new CborDecimalFraction(BigInteger.Parse(mantissa), exponent), value);
        }

        [Fact]
        public void ReadNullableNull()
        {
            Assert.Null(Helper.Read<CborDecimalFraction?>("F6"));
        }

        /// <summary>
        /// A <see cref="decimal"/> member under <c>DecimalFormat.DecimalFraction</c> and a
        /// <see cref="CborDecimalFraction"/> member write the same tag 4 bytes for the same value, and
        /// each reads what the other wrote. Neither shadows the other: which converter runs is settled
        /// by the declared type, in <c>PrimitiveConverterProvider</c>.
        /// </summary>
        /// <remarks>
        /// Asserted rather than inferred from where the dispatch happens. The two encodings arrived
        /// separately -- the <see cref="decimal"/> half in #206, these types in #170 -- so nothing else
        /// holds them to one wire form, and a divergence would be invisible to either file's own tests.
        /// </remarks>
        [Fact]
        public void ADecimalMemberAndAFractionMemberWriteTheSameBytes()
        {
            CborOptions options = new CborOptions { DecimalFormat = DecimalFormat.DecimalFraction };

            Assert.Equal(
                Helper.Write(273.15m, options),
                Helper.Write(new CborDecimalFraction(27315, -2)),
                ignoreCase: true);

            // And each reads the other's bytes, as far as its own type reaches.
            Assert.Equal(273.15m, Helper.Read<decimal>("C48221196AB3", options));
            Assert.Equal(new CborDecimalFraction(27315, -2), Helper.Read<CborDecimalFraction>("C48221196AB3"));
        }

        /// <summary>
        /// Nothing about the object model changes: a tag 4 still reads into a <c>CborValue</c> as the
        /// two-element array it is encoded as, and the tag still survives the write, as it has since
        /// #165. Only a member <em>typed</em> as one of these structs gains semantics.
        /// </summary>
        [Fact]
        public void TheObjectModelStillSeesADecimalFractionAsATaggedArray()
        {
            ObjectModel.CborValue value = Helper.Read<ObjectModel.CborValue>("C48221196AB3");

            Assert.Equal(ObjectModel.CborValueType.Array, value.Type);
            Assert.Equal("C48221196AB3", Helper.Write(value), ignoreCase: true);
        }

        [Fact]
        public void GeneratedContextRoundTrip()
        {
            FractionContext context = new FractionContext();

            GeneratedFractionHolder holder = new GeneratedFractionHolder
            {
                Price = new CborDecimalFraction(27315, -2),
                Scale = new CborBigFloat(3, -1),
                Optional = new CborDecimalFraction(BigInteger.Parse("18446744073709551616"), -3),
            };

            string hexBuffer = Helper.Write(holder, context.Options);
            GeneratedFractionHolder read = Helper.Read<GeneratedFractionHolder>(hexBuffer, context.Options);

            Assert.Equal(holder.Price, read.Price);
            Assert.Equal(holder.Scale, read.Scale);
            Assert.Equal(holder.Optional, read.Optional);

            // The bytes the reflection path writes, which is the assertion that catches the two types
            // being collected as objects rather than as primitives.
            Assert.Equal(hexBuffer, Helper.Write(holder), ignoreCase: true);
        }
    }
}
