using Dahomey.Cbor.Attributes;
using Dahomey.Cbor.Serialization;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Numerics;
using Xunit;

namespace Dahomey.Cbor.Tests
{
    public class GeneratedFractionHolder
    {
        public CborDecimalFraction Price { get; set; }
        public CborBigFloat Scale { get; set; }
        public CborDecimalFraction? Optional { get; set; }
    }

    /// <summary>
    /// Exercises the source-generated path, which is the half a run-time test cannot reach.
    /// </summary>
    /// <remarks>
    /// The regression this guards is silent. Both types are non-generic structs, so without an entry in
    /// <c>TypeCollector.IsPrimitive</c> they are not classified unsupported -- <c>Classify</c> falls
    /// through to <c>TypeKind.Object</c>, the build succeeds, and the emitted context writes
    /// <c>Mantissa</c> and <c>Exponent</c> as a map behind CBOR1006 warnings. Green build, wrong bytes.
    /// What catches it is <see cref="FractionTypeTests.GeneratedContextRoundTrip"/> and the
    /// <c>GeneratedCorpusTests</c> cases, which compare the generated bytes against the reflection
    /// path's.
    /// </remarks>
    [CborSerializable(typeof(GeneratedFractionHolder))]
    public partial class FractionContext : CborSerializerContext
    {
    }

    /// <summary>
    /// One type carrying both encodings of tag 4: a <see cref="decimal"/>, whose form is chosen by
    /// <c>CborOptions.DecimalFormat</c>, and the two §3.4.4 structs, whose form is fixed by their type.
    /// </summary>
    public class GeneratedMixedHolder
    {
        [CborProperty("d")]
        public decimal Plain { get; set; }

        [CborProperty("f")]
        public CborDecimalFraction Fraction { get; set; }

        [CborProperty("b")]
        public CborBigFloat Big { get; set; }
    }

    /// <summary>
    /// The generated half of the cohabitation, which needs its own context because the generator
    /// collects types through <c>TypeCollector</c> and takes the setting from this attribute rather
    /// than from a <see cref="CborOptions"/> instance -- two mechanisms that meet only here.
    /// </summary>
    [CborSerializable(typeof(GeneratedMixedHolder))]
    [CborSourceGenerationOptions(DecimalFormat = DecimalFormat.DecimalFraction)]
    public partial class MixedFractionContext : CborSerializerContext
    {
    }

    /// <summary>
    /// The same type again with the setting left alone, so the contrast is between two generated
    /// contexts rather than between a generated one and a reflected one.
    /// </summary>
    [CborSerializable(typeof(GeneratedMixedHolder))]
    public partial class MixedDefaultContext : CborSerializerContext
    {
    }

    /// <summary>
    /// The two RFC 8949 §3.4.4 types, <see cref="CborDecimalFraction"/> (tag 4) and
    /// <see cref="CborBigFloat"/> (tag 5). The hex buffers for <c>273.15</c> and <c>1.5</c> are the ones
    /// §3.4.4 spells out.
    /// </summary>
    /// <remarks>
    /// <c>DecimalFractionTests</c> is the neighbouring file and covers the other half of tag 4: what a
    /// member typed <see cref="decimal"/> writes under <c>CborOptions.DecimalFormat</c> and reads back.
    /// The two agree on the bytes and differ in what they can hold, which
    /// <see cref="ADecimalMemberAndAFractionMemberWriteTheSameBytes"/> pins.
    /// </remarks>
    public class FractionTypeTests
    {
        public class ObjectWithFractions
        {
            [CborProperty("p")]
            public CborDecimalFraction Price { get; set; }

            [CborProperty("s")]
            public CborBigFloat Scale { get; set; }
        }

        [Theory]
        [InlineData("C48221196AB3", "27315", -2)]      // 273.15, RFC 8949 section 3.4.4
        [InlineData("C4820000", "0", 0)]
        [InlineData("C482000A", "10", 0)]
        [InlineData("C4820101", "1", 1)]
        [InlineData("C48220182D", "45", -1)]                         // 4.5
        [InlineData("C482002B", "-12", 0)]
        [InlineData("C48221C249010000000000000000", "18446744073709551616", -2)]
        public void ReadDecimalFraction(string hexBuffer, string mantissa, int exponent)
        {
            Helper.TestRead(hexBuffer, new CborDecimalFraction(BigInteger.Parse(mantissa), exponent));
        }

        [Theory]
        [InlineData("C5822003", "3", -1)]              // 1.5, RFC 8949 section 3.4.4
        [InlineData("C5820000", "0", 0)]
        [InlineData("C58200C249010000000000000000", "18446744073709551616", 0)]
        public void ReadBigFloat(string hexBuffer, string mantissa, int exponent)
        {
            Helper.TestRead(hexBuffer, new CborBigFloat(BigInteger.Parse(mantissa), exponent));
        }

        [Theory]
        [InlineData("27315", -2, "C48221196AB3")]
        [InlineData("0", 0, "C4820000")]
        [InlineData("-12", 0, "C482002B")]
        // Past a basic integer, so the mantissa takes a bignum tag of its own -- which is
        // WriteBigInteger's decision, not this writer's, and is what section 3.4.4 permits.
        [InlineData("18446744073709551616", -1, "C48220C249010000000000000000")]
        [InlineData("79228162514264337593543950335", 0, "C48200C24CFFFFFFFFFFFFFFFFFFFFFFFF")]
        public void WriteDecimalFraction(string mantissa, int exponent, string expectedHexBuffer)
        {
            Helper.TestWrite(new CborDecimalFraction(BigInteger.Parse(mantissa), exponent), expectedHexBuffer);
        }

        [Theory]
        [InlineData("3", -1, "C5822003")]
        [InlineData("1", 96, "C582186001")]
        public void WriteBigFloat(string mantissa, int exponent, string expectedHexBuffer)
        {
            Helper.TestWrite(new CborBigFloat(BigInteger.Parse(mantissa), exponent), expectedHexBuffer);
        }

        /// <summary>
        /// A document is re-emitted as it arrived, mantissa and exponent untouched. Two encodings of ten
        /// stay two encodings of ten: normalising would make the type lossy in the way mapping onto
        /// <see cref="decimal"/> would.
        /// </summary>
        [Theory]
        [InlineData("C482000A")]
        [InlineData("C4820101")]
        [InlineData("C48221196AB3")]
        public void ANonNormalisedValueRoundTripsUnchanged(string hexBuffer)
        {
            Assert.Equal(hexBuffer, Helper.Write(Helper.Read<CborDecimalFraction>(hexBuffer)),
                ignoreCase: true);
        }

        [Fact]
        public void ABigFloatRoundTripsUnchanged()
        {
            Assert.Equal("C5822003", Helper.Write(Helper.Read<CborBigFloat>("C5822003")), ignoreCase: true);
        }

        /// <summary>
        /// The tag is required: it is the only thing separating either value from the plain two-element
        /// array it is encoded as, and the innermost of tags 4 and 5 decides, so the other kind is
        /// refused rather than reinterpreted.
        /// </summary>
        [Theory]
        [InlineData("8221196AB3")]              // no tag at all
        [InlineData("C5822003")]                // tag 5 read as a decimal fraction
        [InlineData("C4C58221196AB3")]          // innermost is tag 5
        [InlineData("C1C58221196AB3")]          // foreign tag over tag 5
        public void ADecimalFractionNeedsTagFour(string hexBuffer)
        {
            Assert.Throws<CborException>(() => Helper.Read<CborDecimalFraction>(hexBuffer));
        }

        /// <summary>
        /// The whole tag stack is read, as everywhere since #183, so a value under an outer tag is not
        /// the one shape this reader alone refuses. A foreign tag between tag 4 and its content array is
        /// skipped for the same reason it is skipped anywhere else.
        /// </summary>
        [Theory]
        [InlineData("C1C48221196AB3")]          // foreign tag over tag 4
        [InlineData("C4C18221196AB3")]          // foreign tag under tag 4
        [InlineData("C5C48221196AB3")]          // tag 5 outside, tag 4 nearest the data
        [InlineData("C48221C1196AB3")]          // foreign tag on the mantissa
        public void ADecimalFractionIsReadThroughTheTagStack(string hexBuffer)
        {
            Helper.TestRead(hexBuffer, new CborDecimalFraction(27315, -2));
        }

        /// <summary>
        /// An indefinite-length content array is accepted -- §3.4.4 does not forbid one, and the reader
        /// is lenient about indefinite lengths everywhere else -- but it still has to hold exactly two
        /// items, and the break has to be consumed or the item after it reads as part of this one.
        /// </summary>
        [Fact]
        public void AnIndefiniteLengthContentArrayIsRead()
        {
            Helper.TestRead("C49F21196AB3FF", new CborDecimalFraction(27315, -2));
        }

        [Fact]
        public void AnIndefiniteLengthContentArrayLeavesNothingBehind()
        {
            List<CborDecimalFraction> read = Helper.Read<List<CborDecimalFraction>>(
                "82C49F21196AB3FFC49F2003FF");

            Assert.Equal(new CborDecimalFraction(27315, -2), read[0]);
            Assert.Equal(new CborDecimalFraction(3, -1), read[1]);
        }

        [Theory]
        [InlineData("C483211903E800")]          // three items
        [InlineData("C48121")]                  // one item
        [InlineData("C48021196AB3")]            // empty, then two stray items
        [InlineData("C49FFF")]                  // indefinite, empty
        [InlineData("C49F21FF")]                // indefinite, one item
        [InlineData("C49F21196AB300FF")]        // indefinite, three items
        [InlineData("C40C")]                    // not an array at all
        public void AContentArrayOfAnyOtherLengthIsRefused(string hexBuffer)
        {
            Assert.Throws<CborException>(() => Helper.Read<CborDecimalFraction>(hexBuffer));
        }

        /// <summary>
        /// §3.4.4 requires the exponent to be a basic integer, which is what reading it as an
        /// <see cref="int"/> enforces -- a bignum-tagged exponent is a byte string and fails on major
        /// type. The <see cref="int"/> itself is a narrowing of the format, which permits major type 0
        /// or 1 and so reaches ±2^64: a conforming document beyond ±2^31 is refused rather than read.
        /// </summary>
        [Theory]
        [InlineData("C4821B000000010000000001")]    // exponent 2^32
        [InlineData("C4823B000000010000000001")]    // exponent -2^32 - 1
        [InlineData("C482C2410101")]                // exponent as a tagged bignum
        [InlineData("C482614101")]                  // exponent as a text string
        public void AnExponentOutsideInt32IsRefused(string hexBuffer)
        {
            Assert.Throws<CborException>(() => Helper.Read<CborDecimalFraction>(hexBuffer));
        }

        /// <summary>
        /// Equality is structural over the pair as encoded, so two encodings of one number are not
        /// equal. Stated and pinned because it decides behaviour as a dictionary key and under
        /// <c>Deterministic</c>, where they sort as the different byte strings they are.
        /// </summary>
        [Fact]
        public void TwoEncodingsOfOneNumberAreNotEqual()
        {
            CborDecimalFraction ten = new CborDecimalFraction(10, 0);
            CborDecimalFraction alsoTen = new CborDecimalFraction(1, 1);

            Assert.NotEqual(ten, alsoTen);
            Assert.False(ten == alsoTen);
            Assert.Equal(ten.ToDecimal(), alsoTen.ToDecimal());
            Assert.Equal(new CborDecimalFraction(10, 0), ten);
            Assert.Equal(new CborDecimalFraction(10, 0).GetHashCode(), ten.GetHashCode());
        }

        [Fact]
        public void ADecimalFractionIsExactlyADecimalWhereThereIsOne()
        {
            Assert.Equal(273.15m, new CborDecimalFraction(27315, -2).ToDecimal());
            Assert.Equal(0m, new CborDecimalFraction(0, 5).ToDecimal());
            Assert.Equal(-12m, new CborDecimalFraction(-12, 0).ToDecimal());
            Assert.Equal(1000m, new CborDecimalFraction(1, 3).ToDecimal());
            Assert.Equal(
                79228162514264337593543950335m,
                new CborDecimalFraction(BigInteger.Parse("79228162514264337593543950335"), 0).ToDecimal());
        }

        /// <summary>
        /// An exponent below -28 is not by itself fatal: a mantissa with trailing zeros gives the scale
        /// back, so <c>1000e-30</c> is the representable <c>1e-27</c>.
        /// </summary>
        [Fact]
        public void AScaleThatReducesToTwentyEightIsRepresentable()
        {
            Assert.Equal(1e-27m, new CborDecimalFraction(1000, -30).ToDecimal());
        }

        /// <summary>
        /// A mantissa the size of a real document, reduced in one division rather than one per digit.
        /// </summary>
        /// <remarks>
        /// The size is the test. Each big-integer division is O(n) in the mantissa, so giving digits back
        /// one at a time is quadratic in the size of the document the mantissa came from: measured on
        /// net10.0, 40,000 digits took 513 ms that way, 80,000 took 2.0 s and 160,000 took 8.0 s, against
        /// 3, 3 and 11 ms bounded. The same shape reaches <see cref="CborBigFloat"/> through
        /// <c>2^k × 2^-k</c>, which is why both are here. An application calling either conversion on a
        /// value it decoded is the ordinary thing to do, so the amplification is reachable from a
        /// document.
        /// </remarks>
        [Fact]
        public void AMantissaWithManyTrailingZerosReducesInOneStep()
        {
            BigInteger tenToThe100000 = BigInteger.Pow(10, 100000);

            Assert.Equal(1e-28m, new CborDecimalFraction(tenToThe100000, -100028).ToDecimal());
            Assert.Equal(1m, new CborBigFloat(BigInteger.Pow(2, 100000), -100000).ToDecimal());
            Assert.Equal(1.0, new CborBigFloat(BigInteger.Pow(2, 100000), -100000).ToDouble());

            // And a digit that is not zero still refuses, rather than the reduction quietly dropping it.
            Assert.Throws<OverflowException>(() => new CborDecimalFraction(tenToThe100000 + 1, -100028).ToDecimal());
        }

        /// <summary>
        /// A <see cref="double"/> converted to a fraction and back is the same <see cref="double"/>, at
        /// any mantissa width. Padding the mantissa with zeros and lowering the exponent leaves the
        /// value alone, so the expected answer is known however long the digits run.
        /// </summary>
        /// <remarks>
        /// The padding is what makes this a test of long mantissas with a knowable answer, rather than
        /// one that has to trust another conversion to say what the answer is. It covers both ends of
        /// the range: <see cref="double.Epsilon"/> and the value below the smallest normal exercise the
        /// subnormal grid, where the rounding position is set by 2^-1074 rather than by 53 significant
        /// bits, and <see cref="double.MaxValue"/> exercises the top without tipping into the overflow
        /// check.
        /// </remarks>
        [Theory]
        [InlineData(0.1, 0)]
        [InlineData(0.1, 2000)]
        [InlineData(1.5, 0)]
        [InlineData(1.5, 2000)]
        [InlineData(-273.15, 500)]
        [InlineData(double.MaxValue, 0)]
        [InlineData(double.MaxValue, 400)]
        [InlineData(double.Epsilon, 0)]
        [InlineData(double.Epsilon, 500)]
        [InlineData(2.2250738585072014E-308, 300)]   // the smallest normal
        [InlineData(1E-320, 300)]                    // subnormal
        public void ADoubleSurvivesAFractionOfAnyWidth(double value, int padding)
        {
            CborDecimalFraction fraction = (CborDecimalFraction)value;
            CborDecimalFraction padded = new CborDecimalFraction(
                fraction.Mantissa * BigInteger.Pow(10, padding), fraction.Exponent - padding);

            Assert.Equal(value, padded.ToDouble());
        }

        /// <summary>
        /// The conversion agrees with the platform's own parser over a spread of ordinary values, which
        /// is the oracle for everything the cases above do not name individually.
        /// </summary>
        /// <remarks>
        /// Deliberately kept to modest digit counts. <c>double.Parse</c> is only trustworthy as an
        /// oracle where every framework version agrees with it, and .NET 8 does not: a 1,201-digit
        /// mantissa at <c>E-1200</c> — a value just above 1.0 — parses there as <em>zero</em>, where
        /// .NET 9 and .NET 10 are right. That is why this type does its own arithmetic rather than
        /// rendering and parsing, and why the oracle is used only where it can be trusted.
        /// </remarks>
        [Fact]
        public void OrdinaryValuesAgreeWithThePlatformParser()
        {
            Random random = new Random(20260813);

            for (int iteration = 0; iteration < 2000; iteration++)
            {
                BigInteger mantissa = new BigInteger(random.NextInt64());
                int exponent = random.Next(-25, 26);

                string rendered = mantissa.ToString(CultureInfo.InvariantCulture)
                    + "E" + exponent.ToString(CultureInfo.InvariantCulture);
                double expected = double.Parse(rendered, NumberStyles.Float, CultureInfo.InvariantCulture);

                Assert.Equal(expected, new CborDecimalFraction(mantissa, exponent).ToDouble());
            }
        }

        /// <summary>
        /// The case the cap's trailing marker exists for: a value a hair above the midpoint between two
        /// doubles, where the hair is further out than the cap keeps.
        /// </summary>
        /// <remarks>
        /// The midpoint itself is exactly representable as a decimal fraction — it is an odd multiple of
        /// a power of two, and <c>2^-n = 5^n × 10^-n</c> — and rounds to even, which is <c>1.0</c> here.
        /// Adding one unit 2,000 digits further down leaves a value that must round the other way, to
        /// the double above. A truncation that dropped those digits silently would land back on the
        /// midpoint and round to even, one ulp low; the appended non-zero digit is what prevents it.
        /// </remarks>
        [Fact]
        public void AValueJustAboveAMidpointStillRoundsAwayFromIt()
        {
            // The double above 1.0 is 1 + 2^-52, so the midpoint is 1 + 2^-53 = (2^53 + 1) * 2^-53.
            // Built as a decimal fraction rather than through a double, so nothing has rounded yet:
            // (2^53 + 1) * 5^53 * 10^-53 is that value exactly.
            const int binaryExponent = 53;
            BigInteger midpointMantissa =
                ((BigInteger.One << binaryExponent) + 1) * BigInteger.Pow(5, binaryExponent);
            int midpointExponent = -binaryExponent;

            // Exactly on the midpoint: ties go to even, and 1.0 is the even one.
            Assert.Equal(1.0, new CborDecimalFraction(midpointMantissa, midpointExponent).ToDouble());

            // One unit 2,000 decimal places below that, which is well past the cap: the value is above
            // the midpoint and must round to the double above.
            BigInteger justAbove = midpointMantissa * BigInteger.Pow(10, 2000) + 1;

            Assert.Equal(
                Math.BitIncrement(1.0),
                new CborDecimalFraction(justAbove, midpointExponent - 2000).ToDouble());

            // The same construction one unit below the midpoint rounds down to 1.0, which is the
            // assertion that fails if the marker is appended unconditionally rather than only when
            // something was dropped.
            BigInteger justBelow = midpointMantissa * BigInteger.Pow(10, 2000) - 1;

            Assert.Equal(1.0, new CborDecimalFraction(justBelow, midpointExponent - 2000).ToDouble());
        }

        [Theory]
        [InlineData("3", -29)]                                      // scale will not reduce
        [InlineData("1", 29)]                                       // past decimal.MaxValue
        [InlineData("79228162514264337593543950336", 0)]            // mantissa wider than 96 bits
        public void ADecimalFractionWithNoDecimalThrowsRatherThanRounding(string mantissa, int exponent)
        {
            CborDecimalFraction value = new CborDecimalFraction(BigInteger.Parse(mantissa), exponent);

            Assert.Throws<OverflowException>(() => value.ToDecimal());
        }

        [Fact]
        public void ADecimalFractionConvertsToTheNearestDouble()
        {
            Assert.Equal(273.15, new CborDecimalFraction(27315, -2).ToDouble());
            Assert.Equal(0.1, new CborDecimalFraction(1, -1).ToDouble());
            Assert.Equal(0.0, new CborDecimalFraction(1, -400).ToDouble());
            Assert.Throws<OverflowException>(() => new CborDecimalFraction(1, 400).ToDouble());
        }

        /// <summary>
        /// Exact, which is worth pinning because it looks as though it could not be: a
        /// <see cref="double"/> is <c>m × 2^e</c> and <c>2^-n = 5^n × 10^-n</c>, so <c>0.1</c> lands as
        /// its true value rather than as <c>1e-1</c>.
        /// </summary>
        [Fact]
        public void ADoubleConvertsExactlyToBothTypes()
        {
            Assert.Equal(new CborBigFloat(3602879701896397, -55), (CborBigFloat)0.1);
            Assert.Equal(new CborBigFloat(3, -1), (CborBigFloat)1.5);

            CborDecimalFraction tenth = (CborDecimalFraction)0.1;

            Assert.Equal(-55, tenth.Exponent);
            Assert.Equal(3602879701896397 * BigInteger.Pow(5, 55), tenth.Mantissa);
            Assert.Equal(0.1, tenth.ToDouble());
        }

        [Fact]
        public void ADecimalConvertsExactlyToADecimalFraction()
        {
            Assert.Equal(new CborDecimalFraction(27315, -2), (CborDecimalFraction)273.15m);
            Assert.Equal(new CborDecimalFraction(0, -2), (CborDecimalFraction)0.00m);
            Assert.Equal(new CborDecimalFraction(-27315, -2), (CborDecimalFraction)(-273.15m));
        }

        /// <summary>
        /// There is no conversion from <see cref="decimal"/> to <see cref="CborBigFloat"/>, and its
        /// absence is a decision: it cannot be exact, because <c>m × 2^e = 1/10</c> has no integer
        /// solution. Asserted rather than left to the comment, since adding the operator would compile
        /// and would silently round.
        /// </summary>
        [Fact]
        public void ThereIsNoConversionFromDecimalToABigFloat()
        {
            foreach (System.Reflection.MethodInfo method in typeof(CborBigFloat).GetMethods())
            {
                if (method.Name == "op_Explicit" || method.Name == "op_Implicit")
                {
                    Assert.NotEqual(typeof(decimal), Assert.Single(method.GetParameters()).ParameterType);
                }
            }
        }

        [Theory]
        [InlineData(double.NaN)]
        [InlineData(double.PositiveInfinity)]
        [InlineData(double.NegativeInfinity)]
        public void ADoubleWithNoFiniteValueHasNoFraction(double value)
        {
            Assert.Throws<OverflowException>(() => (CborDecimalFraction)value);
            Assert.Throws<OverflowException>(() => (CborBigFloat)value);
        }

        /// <summary>
        /// Factors of two come out of the mantissa first, so a large negative exponent does not by
        /// itself put a value out of reach: <c>2^100 × 2^-100</c> is one.
        /// </summary>
        [Fact]
        public void ABigFloatIsExactlyADecimalWhereThereIsOne()
        {
            Assert.Equal(1.5m, new CborBigFloat(3, -1).ToDecimal());
            Assert.Equal(0m, new CborBigFloat(0, -1000).ToDecimal());
            Assert.Equal(1m, new CborBigFloat(BigInteger.Pow(2, 100), -100).ToDecimal());
            Assert.Equal(1.5, new CborBigFloat(3, -1).ToDouble());
        }

        /// <summary>
        /// <c>0.1</c> as a <see cref="double"/> is a bigfloat with an odd mantissa over 2^55, and no
        /// <see cref="decimal"/> has that value -- the scale it needs is 55, not 28. So the exact
        /// conversion refuses rather than handing back <c>0.1m</c>, which is a different number.
        /// </summary>
        [Fact]
        public void ABigFloatWithNoDecimalThrowsRatherThanRounding()
        {
            Assert.Throws<OverflowException>(() => ((CborBigFloat)0.1).ToDecimal());
            Assert.Equal(0.1, ((CborBigFloat)0.1).ToDouble());
        }

        [Fact]
        public void ABigFloatOutsideDoubleIsRefusedRatherThanInfinite()
        {
            Assert.Throws<OverflowException>(() => new CborBigFloat(1, 2000).ToDouble());
            Assert.Equal(0.0, new CborBigFloat(1, -2000).ToDouble());
        }

        [Fact]
        public void ReadObject()
        {
            ObjectWithFractions obj = Helper.Read<ObjectWithFractions>("A26170C48221196AB36173C5822003");

            Assert.Equal(new CborDecimalFraction(27315, -2), obj.Price);
            Assert.Equal(new CborBigFloat(3, -1), obj.Scale);
        }

        [Fact]
        public void WriteObject()
        {
            ObjectWithFractions obj = new ObjectWithFractions
            {
                Price = new CborDecimalFraction(27315, -2),
                Scale = new CborBigFloat(3, -1),
            };

            Helper.TestWrite(obj, "A26170C48221196AB36173C5822003");
        }

        /// <summary>
        /// The shape that failed for <see cref="BigInteger"/>: <c>NullableConverter</c> skips a semantic
        /// tag before looking for null, which loses the tag for a converter that dispatches on one. The
        /// bookmark path it took to fix that has to hold here too, since both of these dispatch on a tag.
        /// </summary>
        [Theory]
        [InlineData("C48221196AB3", "27315", -2)]
        [InlineData("C1C48221196AB3", "27315", -2)]
        public void ReadNullable(string hexBuffer, string mantissa, int exponent)
        {
            CborDecimalFraction? value = Helper.Read<CborDecimalFraction?>(hexBuffer);

            Assert.Equal(new CborDecimalFraction(BigInteger.Parse(mantissa), exponent), value);
        }

        [Fact]
        public void ReadNullableNull()
        {
            Assert.Null(Helper.Read<CborDecimalFraction?>("F6"));
        }

        /// <summary>
        /// A <see cref="decimal"/> member under <c>DecimalFormat.DecimalFraction</c> and a
        /// <see cref="CborDecimalFraction"/> member write the same tag 4 bytes for the same value, and
        /// each reads what the other wrote. Neither shadows the other: which converter runs is settled
        /// by the declared type, in <c>PrimitiveConverterProvider</c>.
        /// </summary>
        /// <remarks>
        /// Asserted rather than inferred from where the dispatch happens. The two encodings arrived
        /// separately -- the <see cref="decimal"/> half in #206, these types in #170 -- so nothing else
        /// holds them to one wire form, and a divergence would be invisible to either file's own tests.
        /// </remarks>
        [Fact]
        public void ADecimalMemberAndAFractionMemberWriteTheSameBytes()
        {
            CborOptions options = new CborOptions { DecimalFormat = DecimalFormat.DecimalFraction };

            Assert.Equal(
                Helper.Write(273.15m, options),
                Helper.Write(new CborDecimalFraction(27315, -2)),
                ignoreCase: true);

            // And each reads the other's bytes, as far as its own type reaches.
            Assert.Equal(273.15m, Helper.Read<decimal>("C48221196AB3", options));
            Assert.Equal(new CborDecimalFraction(27315, -2), Helper.Read<CborDecimalFraction>("C48221196AB3"));
        }

        /// <summary>
        /// Both encodings of tag 4 in one document: a <see cref="decimal"/> member beside a
        /// <see cref="CborDecimalFraction"/> and a <see cref="CborBigFloat"/> one, written and read back
        /// together.
        /// </summary>
        /// <remarks>
        /// <see cref="ADecimalMemberAndAFractionMemberWriteTheSameBytes"/> writes the two separately,
        /// which settles the bytes but not the cohabitation: it never has both converters registered
        /// against one object mapping at once. The value of doing it in a single type is that the
        /// members are resolved together, so a provider that answered for the wrong one would show up
        /// here and nowhere else.
        /// </remarks>
        [Fact]
        public void ADecimalAndTheFractionTypesCoexistInOneObject()
        {
            CborOptions options = new CborOptions { DecimalFormat = DecimalFormat.DecimalFraction };

            GeneratedMixedHolder holder = new GeneratedMixedHolder
            {
                Plain = 273.15m,
                Fraction = new CborDecimalFraction(27315, -2),
                Big = new CborBigFloat(3, -1),
            };

            // The decimal and the fraction are the same six bytes, twice over, under different names.
            Assert.Equal(
                "A36164C48221196AB36166C48221196AB36162C5822003",
                Helper.Write(holder, options),
                ignoreCase: true);

            GeneratedMixedHolder read = Helper.Read<GeneratedMixedHolder>(Helper.Write(holder, options), options);

            Assert.Equal(holder.Plain, read.Plain);
            Assert.Equal(holder.Fraction, read.Fraction);
            Assert.Equal(holder.Big, read.Big);
        }

        /// <summary>
        /// <c>CborOptions.DecimalFormat</c> governs the <see cref="decimal"/> member and nothing else.
        /// Under the default the decimal goes back to the <c>FC</c> form while the two struct members
        /// stay on tags 4 and 5, in the same document.
        /// </summary>
        /// <remarks>
        /// This is the assertion behind "neither shadows the other". The two mechanisms select on
        /// different things -- an option for the one, the declared type for the others -- and the way
        /// that would break is the option leaking across, which only shows when one document contains
        /// both and the option is set the way that makes them differ.
        /// </remarks>
        [Fact]
        public void TheDecimalFormatDoesNotReachTheFractionTypes()
        {
            GeneratedMixedHolder holder = new GeneratedMixedHolder
            {
                Plain = 273.15m,
                Fraction = new CborDecimalFraction(27315, -2),
                Big = new CborBigFloat(3, -1),
            };

            Assert.Equal(
                "A36164FC0000000000006AB300000000000200006166C48221196AB36162C5822003",
                Helper.Write(holder),
                ignoreCase: true);

            GeneratedMixedHolder read = Helper.Read<GeneratedMixedHolder>(Helper.Write(holder));

            Assert.Equal(holder.Plain, read.Plain);
            Assert.Equal(holder.Fraction, read.Fraction);
            Assert.Equal(holder.Big, read.Big);
        }

        /// <summary>
        /// The three members round-trip together under <c>CborOptions.Deterministic</c>, where the map
        /// keys are reordered and the bytes are the ones the ordering was computed over.
        /// </summary>
        [Fact]
        public void TheFractionTypesCoexistUnderDeterministic()
        {
            CborOptions options = new CborOptions
            {
                DecimalFormat = DecimalFormat.DecimalFraction,
                Deterministic = true,
            };

            GeneratedMixedHolder holder = new GeneratedMixedHolder
            {
                Plain = 273.15m,
                Fraction = new CborDecimalFraction(27315, -2),
                Big = new CborBigFloat(3, -1),
            };

            // Keys in length-then-bytewise order: "b", "d", "f".
            Assert.Equal(
                "A36162C58220036164C48221196AB36166C48221196AB3",
                Helper.Write(holder, options),
                ignoreCase: true);

            GeneratedMixedHolder read = Helper.Read<GeneratedMixedHolder>(Helper.Write(holder, options), options);

            Assert.Equal(holder.Plain, read.Plain);
            Assert.Equal(holder.Fraction, read.Fraction);
            Assert.Equal(holder.Big, read.Big);
        }

        /// <summary>
        /// The cohabitation holds on the generated path too, with both settings.
        /// </summary>
        /// <remarks>
        /// The half a run-time test cannot reach, and the two mechanisms are independent there in a way
        /// they are not at run time: <c>TypeCollector</c> decides that the two structs are primitives,
        /// while <c>DecimalFormat</c> travels from the attribute into the emitted registrations. A
        /// generated context could get either right and the other wrong -- collecting the structs as
        /// objects, or dropping the setting -- and the reflection bytes are what catches both, since
        /// they are the same document by construction.
        /// </remarks>
        [Fact]
        public void TheGeneratedPathAgreesOnBothEncodingsOfTagFour()
        {
            GeneratedMixedHolder holder = new GeneratedMixedHolder
            {
                Plain = 273.15m,
                Fraction = new CborDecimalFraction(27315, -2),
                Big = new CborBigFloat(3, -1),
            };

            MixedFractionContext fractionContext = new MixedFractionContext();
            CborOptions fractionOptions = new CborOptions { DecimalFormat = DecimalFormat.DecimalFraction };

            Assert.Equal(
                Helper.Write(holder, fractionOptions),
                Helper.Write(holder, fractionContext.Options),
                ignoreCase: true);

            MixedDefaultContext defaultContext = new MixedDefaultContext();

            Assert.Equal(
                Helper.Write(holder),
                Helper.Write(holder, defaultContext.Options),
                ignoreCase: true);

            // And back, through the generated readers rather than the reflection ones.
            GeneratedMixedHolder read = Helper.Read<GeneratedMixedHolder>(
                Helper.Write(holder, fractionContext.Options), fractionContext.Options);

            Assert.Equal(holder.Plain, read.Plain);
            Assert.Equal(holder.Fraction, read.Fraction);
            Assert.Equal(holder.Big, read.Big);
        }

        /// <summary>
        /// One document, two ways of asking for a <see cref="decimal"/>, one answer. A tag 4 read into a
        /// <see cref="decimal"/> member goes through <c>CborReader</c>'s own conversion; the same bytes
        /// read into this type and then converted go through <see cref="CborDecimalFraction.ToDecimal"/>.
        /// Both are exact-or-refuse, and they have to agree on which.
        /// </summary>
        /// <remarks>
        /// A differential test rather than two tables of expectations, because the two implementations
        /// arrived separately -- #206 and #170 -- and nothing else holds them together. It caught a real
        /// divergence: <c>[-1, 10^29]</c> is <c>1E+28</c>, which a <see cref="decimal"/> holds once the
        /// scale is given back to the mantissa's width, and only the reader did that. The exception types
        /// differ by design and are not compared: a read failure is a <see cref="CborException"/>, a
        /// conversion failure an <see cref="OverflowException"/>.
        /// </remarks>
        [Theory]
        [InlineData("27315", -2)]
        [InlineData("-27315", -2)]
        // Inside the scale limit and too wide, so the width is fixed by giving the scale back.
        [InlineData("100000000000000000000000000000", -1)]
        [InlineData("10000000000000000000000000000000", -3)]
        // Past the scale limit, with trailing zeros to give back.
        [InlineData("1000", -30)]
        // Neither is available: refused by both.
        [InlineData("3", -29)]
        [InlineData("79228162514264337593543950336", 0)]
        public void ADecimalMemberAndToDecimalAgree(string mantissaText, int exponent)
        {
            BigInteger mantissa = BigInteger.Parse(mantissaText);
            CborDecimalFraction fraction = new CborDecimalFraction(mantissa, exponent);
            string hexBuffer = Helper.Write(fraction);

            decimal? read = null;
            decimal? converted = null;

            try
            {
                read = Helper.Read<decimal>(hexBuffer);
            }
            catch (CborException)
            {
            }

            try
            {
                converted = fraction.ToDecimal();
            }
            catch (OverflowException)
            {
            }

            Assert.Equal(read, converted);
        }

        /// <summary>
        /// Nothing about the object model changes: a tag 4 still reads into a <c>CborValue</c> as the
        /// two-element array it is encoded as, and the tag still survives the write, as it has since
        /// #165. Only a member <em>typed</em> as one of these structs gains semantics.
        /// </summary>
        [Fact]
        public void TheObjectModelStillSeesADecimalFractionAsATaggedArray()
        {
            ObjectModel.CborValue value = Helper.Read<ObjectModel.CborValue>("C48221196AB3");

            Assert.Equal(ObjectModel.CborValueType.Array, value.Type);
            Assert.Equal("C48221196AB3", Helper.Write(value), ignoreCase: true);
        }

        [Fact]
        public void GeneratedContextRoundTrip()
        {
            FractionContext context = new FractionContext();

            GeneratedFractionHolder holder = new GeneratedFractionHolder
            {
                Price = new CborDecimalFraction(27315, -2),
                Scale = new CborBigFloat(3, -1),
                Optional = new CborDecimalFraction(BigInteger.Parse("18446744073709551616"), -3),
            };

            string hexBuffer = Helper.Write(holder, context.Options);
            GeneratedFractionHolder read = Helper.Read<GeneratedFractionHolder>(hexBuffer, context.Options);

            Assert.Equal(holder.Price, read.Price);
            Assert.Equal(holder.Scale, read.Scale);
            Assert.Equal(holder.Optional, read.Optional);

            // The bytes the reflection path writes, which is the assertion that catches the two types
            // being collected as objects rather than as primitives.
            Assert.Equal(hexBuffer, Helper.Write(holder), ignoreCase: true);
        }
    }
}
