#nullable enable annotations
using System.Text;
using Dahomey.Cbor.Attributes;
using Dahomey.Cbor.Serialization;
using Dahomey.Cbor.Tests.Extensions;
using Xunit;

namespace Dahomey.Cbor.Tests.Cddl
{
    public class CddlPerson
    {
        public string Name { get; set; }
        public int Age { get; set; }
        public byte Rating { get; set; }
        public bool Active { get; set; }
        public double Score { get; set; }
    }

    [CborSerializable(typeof(CddlPerson))]
    [CborCddlSchema]
    public partial class CddlTestContext : CborSerializerContext
    {
    }

    public class CddlSchemaTests
    {
        private static readonly CddlTestContext Context = CborSerializerContext.Default<CddlTestContext>();

        private static CddlPerson SamplePerson() => new CddlPerson
        {
            Name = "Ada",
            Age = 36,
            Rating = 200,
            Active = true,
            Score = 1.5,
        };

        [Fact]
        public void SchemaHeaderNamesTheContractItDescribes()
        {
            Assert.Contains("; Generated by Dahomey.Cbor", CddlTestContext.CddlSchema);
            Assert.Contains("WRITES", CddlTestContext.CddlSchema);
        }

        /// <summary>
        /// Pinned in full, so a change to any emitted byte of the schema is a reviewable diff rather
        /// than something that has to be inferred from a validation failure.
        /// </summary>
        [Fact]
        public void SchemaIsEmittedExactly()
        {
            string expected =
                "CddlPerson = {\n"
                + "  Name: tstr,\n"
                + "  Age: -2147483648..2147483647,\n"
                + "  Rating: 0..255,\n"
                + "  Active: bool,\n"
                + "  Score: float,\n"
                + "}\n";

            Assert.Contains(expected, CddlTestContext.CddlSchema.Replace("\r\n", "\n"));
        }

        [CddlFact]
        public void SerializerOutputValidatesAgainstTheSchema()
        {
            byte[] cbor = Helper.Write(SamplePerson(), Context.Options).HexToBytes();

            CddlResult result = CddlTool.Validate(CddlTestContext.CddlSchema, "CddlPerson", cbor);

            Assert.True(result.Ok, result.Output);
        }

        /// <summary>
        /// Without a negative case the positive one would also pass against a schema of "any", which
        /// is the failure mode that makes a generated schema worse than none.
        /// </summary>
        [CddlFact]
        public void SchemaRejectsADocumentWithTheWrongMemberType()
        {
            // { "Name": 1, "Age": 36, "Rating": 200, "Active": true, "Score": 1.5 }
            // Name is an integer where the schema requires tstr.
            byte[] cbor = "A5644E616D650163416765182466526174696E6718C866416374697665F56553636F7265F93E00".HexToBytes();

            CddlResult result = CddlTool.Validate(CddlTestContext.CddlSchema, "CddlPerson", cbor);

            Assert.False(result.Ok);
        }

        /// <summary>
        /// CborWriter.WriteDouble emits the shortest form that round-trips, in every mode and not only
        /// under Deterministic, so a double of 1.5 goes out as float16. float64 would reject it.
        /// </summary>
        [CddlFact]
        public void DoubleMapsToTheAnyWidthFloat()
        {
            byte[] cbor = Helper.Write(SamplePerson(), Context.Options).HexToBytes();

            Assert.True(CddlTool.Validate(CddlTestContext.CddlSchema, "CddlPerson", cbor).Ok);
            Assert.False(CddlTool.Validate(
                CddlTestContext.CddlSchema.Replace("Score: float", "Score: float64"),
                "CddlPerson",
                cbor).Ok);
        }
    }
}
