using Dahomey.Cbor.Attributes;
using Dahomey.Cbor.Serialization;
using Xunit;

namespace Dahomey.Cbor.Tests.Cddl
{
    public class CddlPerson
    {
        public string Name { get; set; }
    }

    [CborSerializable(typeof(CddlPerson))]
    [CborCddlSchema]
    public partial class CddlTestContext : CborSerializerContext
    {
    }

    /// <summary>
    /// The schema is generated onto the context itself, so these tests exercise the real analyzer
    /// running over this project rather than an in-memory compilation.
    /// </summary>
    public class CddlSchemaTests
    {
        [Fact]
        public void ContextExposesAGeneratedSchema()
        {
            Assert.False(string.IsNullOrWhiteSpace(CddlTestContext.CddlSchema));
        }

        [Fact]
        public void SchemaHeaderNamesTheContractItDescribes()
        {
            Assert.Contains("; Generated by Dahomey.Cbor", CddlTestContext.CddlSchema);
            Assert.Contains("WRITES", CddlTestContext.CddlSchema);
        }
    }
}
