// Governs how CddlPerson.Name (a bare `string`) is read below: with this file's nullable context
// left at the project default (disabled), Name's NullableAnnotation would be `None` and RULING B
// would render it `tstr / nil`, breaking the pinned schema. "annotations", not plain "enable" --
// the annotations-only context records NotAnnotated/Annotated without turning on the warning
// context, so the auto-property below does not need a null-forgiving initializer.
#nullable enable annotations
using Dahomey.Cbor.Attributes;
using Dahomey.Cbor.Serialization;
using Dahomey.Cbor.Tests.Extensions;
using Xunit;

namespace Dahomey.Cbor.Tests.Cddl
{
    public class CddlPerson
    {
        public string Name { get; set; }
        public int Age { get; set; }
        public byte Rating { get; set; }
        public bool Active { get; set; }
        public double Score { get; set; }
    }

    [CborSerializable(typeof(CddlPerson))]
    [CborCddlSchema]
    public partial class CddlTestContext : CborSerializerContext
    {
    }

    public class CddlSchemaTests
    {
        private static readonly CddlTestContext Context = CborSerializerContext.Default<CddlTestContext>();

        private static CddlPerson SamplePerson() => new CddlPerson
        {
            Name = "Ada",
            Age = 36,
            Rating = 200,
            Active = true,
            Score = 1.5,
        };

        [Fact]
        public void SchemaHeaderNamesTheContractItDescribes()
        {
            Assert.Contains("; Generated by Dahomey.Cbor", CddlTestContext.CddlSchema);
            Assert.Contains("WRITES", CddlTestContext.CddlSchema);
        }

        /// <summary>
        /// Pinned in full -- header included, via Assert.Equal against the whole schema rather than
        /// Assert.Contains against one rule -- so a change to any emitted byte (a reordered rule, a
        /// dropped trailing newline, a changed header line) is a reviewable diff rather than something
        /// that has to be inferred from a validation failure. Safe to pin exactly because
        /// CddlTestContext declares only CddlPerson: later tasks add their own contexts rather than
        /// extending this one, so this schema's full text stays stable.
        /// </summary>
        [Fact]
        public void SchemaIsEmittedExactly()
        {
            string expected =
                "; Generated by Dahomey.Cbor. Do not edit.\n"
                + "; Describes what the serializer WRITES: exact and closed.\n"
                + "; Member types follow their nullable annotations. A member declared non-nullable but left\n"
                + "; null at run time is written as F6 and will NOT validate against this schema.\n"
                // No discriminator note: the header describes only the placements this schema uses, and
                // CddlPerson is neither polymorphic nor discriminated. CddlPolymorphismTests covers the
                // lines that appear when it is.
                + "\n"
                + "CddlPerson = {\n"
                + "  \"Name\": tstr,\n"
                + "  \"Age\": -2147483648..2147483647,\n"
                + "  \"Rating\": 0..255,\n"
                + "  \"Active\": bool,\n"
                + "  \"Score\": float,\n"
                + "}\n"
                + "\n";

            Assert.Equal(expected, CddlTestContext.CddlSchema.Replace("\r\n", "\n"));
        }

        [CddlFact]
        public void SerializerOutputValidatesAgainstTheSchema()
        {
            byte[] cbor = Helper.Write(SamplePerson(), Context.Options).HexToBytes();

            CddlResult result = CddlTool.Validate(CddlTestContext.CddlSchema, "CddlPerson", cbor);

            Assert.True(result.Ok, result.Output);
        }

        /// <summary>
        /// Without a negative case the positive one would also pass against a schema of "any", which
        /// is the failure mode that makes a generated schema worse than none.
        /// </summary>
        [CddlFact]
        public void SchemaRejectsADocumentWithTheWrongMemberType()
        {
            // { "Name": 1, "Age": 36, "Rating": 200, "Active": true, "Score": 1.5 }
            // Name is an integer where the schema requires tstr.
            byte[] cbor = "A5644E616D650163416765182466526174696E6718C866416374697665F56553636F7265F93E00".HexToBytes();

            CddlResult result = CddlTool.Validate(CddlTestContext.CddlSchema, "CddlPerson", cbor);

            Assert.False(result.Ok);
        }

        /// <summary>
        /// CborWriter.WriteDouble emits the shortest form that round-trips, in every mode and not only
        /// under Deterministic, so a double of 1.5 goes out as float16. float64 would reject it.
        /// </summary>
        [CddlFact]
        public void DoubleMapsToTheAnyWidthFloat()
        {
            byte[] cbor = Helper.Write(SamplePerson(), Context.Options).HexToBytes();

            Assert.True(CddlTool.Validate(CddlTestContext.CddlSchema, "CddlPerson", cbor).Ok);
            Assert.False(CddlTool.Validate(
                CddlTestContext.CddlSchema.Replace("\"Score\": float", "\"Score\": float64"),
                "CddlPerson",
                cbor).Ok);
        }
    }
}
