name: Build and Test

on:
  push:
    paths:
      - 'src/**'
      - '.github/workflows/**'
    branches:
      - '**'
    tags-ignore:
      - '*.*.*'
  pull_request:
    paths:
      - 'src/**'
      - '.github/workflows/**'
    branches:
      - '**'
    tags-ignore:
      - '*.*.*'

jobs:
  build_and_test:

    runs-on: ubuntu-16.04

    steps:
    - name: checkout
      uses: actions/checkout@v1

    - name: setup .net core 2.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.811

    - name: setup .net core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.404

    - name: setup .net 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100

# workaround for using multiple dotnet core installs
    - name: setup multiple sdks
      run: |
        rsync -a ${DOTNET_ROOT/5.0.100/2.1.811}/* $DOTNET_ROOT/
        rsync -a ${DOTNET_ROOT/5.0.100/3.1.404}/* $DOTNET_ROOT/
        dotnet --info

    - name: build
      run: dotnet build -c Release src/Dahomey.Cbor

    - name: test
      run: dotnet test -c Release src/Dahomey.Cbor.Tests
