name: Deploy to Nuget

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 9.0.x

    - name: build
      run: dotnet pack -p:Version=${GITHUB_REF##*/} -p:FileVersion=${GITHUB_REF##*/} -p:AssemblyVersion=${GITHUB_REF##*/} -c Release src/Dahomey.Cbor

    - name: deploy
      run: dotnet nuget push src/Dahomey.Cbor/bin/Release/Dahomey.Cbor.${GITHUB_REF##*/}.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
